// Code generated by generate-cached. DO NOT EDIT.
package eks

import (
	"fmt"

	awseks "github.com/aws/aws-sdk-go-v2/service/eks"
	"github.com/imunhatep/awslib/cache"
)

// EksRepositoryCached wraps EksRepository and caches results of Get*/List* calls.
type EksRepositoryCached struct {
	repo  *EksRepository
	cache *cache.DataCache
}

// WithCache returns a EksRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EksRepository) WithCache(dc *cache.DataCache) *EksRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EksRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListClustersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EksRepositoryCached) ListClustersAll() ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersAll")
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EksRepositoryCached) ListClustersByInput(query *awseks.ListClustersInput) ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersByInput", query)
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
