// Code generated by generate-cached. DO NOT EDIT.
package emrserverless

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsemr "github.com/aws/aws-sdk-go-v2/service/emrserverless"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// EMRServerlessRepositoryCached wraps EMRServerlessRepository and caches results of Get*/List* calls.
type EMRServerlessRepositoryCached struct {
	repo  *EMRServerlessRepository
	cache *cache.DataCache
}

// WithCache returns a EMRServerlessRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EMRServerlessRepository) WithCache(dc *cache.DataCache) *EMRServerlessRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EMRServerlessRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListApplicationsActive returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListApplicationsActive() ([]Application, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListApplicationsActive"
	var cached []Application
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListApplicationsActive()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListApplicationsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListApplicationsAll(maxResults *int32) ([]Application, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListApplicationsAll:%s", strings.Join([]string{fmt.Sprintf("%+v", maxResults)}, ":")))
	var cached []Application
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListApplicationsAll(maxResults)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListApplicationsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListApplicationsByInput(query *awsemr.ListApplicationsInput) ([]Application, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListApplicationsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Application
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListApplicationsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobRunsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListJobRunsAll() ([]JobRun, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListJobRunsAll"
	var cached []JobRun
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobRunsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobRunsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListJobRunsByInput(query *awsemr.ListJobRunsInput) ([]JobRun, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListJobRunsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []JobRun
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobRunsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
