// Code generated by generate-cached. DO NOT EDIT.
package emrserverless

import (
	"fmt"

	awsemr "github.com/aws/aws-sdk-go-v2/service/emrserverless"
	"github.com/imunhatep/awslib/cache"
)

// EMRServerlessRepositoryCached wraps EMRServerlessRepository and caches results of Get*/List* calls.
type EMRServerlessRepositoryCached struct {
	repo  *EMRServerlessRepository
	cache *cache.DataCache
}

// WithCache returns a EMRServerlessRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:emrserverless".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *EMRServerlessRepository) WithCache(dc *cache.DataCache) *EMRServerlessRepositoryCached {
	ns := fmt.Sprintf("%s:%s:emrserverless", r.client.GetAccountID(), r.client.GetRegion())
	return &EMRServerlessRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListApplicationsActive returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListApplicationsActive() ([]Application, error) {
	cacheKey := cache.Key("ListApplicationsActive")
	var cached []Application
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListApplicationsActive()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListApplicationsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListApplicationsAll(maxResults *int32) ([]Application, error) {
	cacheKey := cache.Key("ListApplicationsAll", maxResults)
	var cached []Application
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListApplicationsAll(maxResults)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListApplicationsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListApplicationsByInput(query *awsemr.ListApplicationsInput) ([]Application, error) {
	cacheKey := cache.Key("ListApplicationsByInput", query)
	var cached []Application
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListApplicationsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobRunsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListJobRunsAll() ([]JobRun, error) {
	cacheKey := cache.Key("ListJobRunsAll")
	var cached []JobRun
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobRunsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobRunsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EMRServerlessRepositoryCached) ListJobRunsByInput(query *awsemr.ListJobRunsInput) ([]JobRun, error) {
	cacheKey := cache.Key("ListJobRunsByInput", query)
	var cached []JobRun
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobRunsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
