//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// outFile is the per-package file this generator owns. Each service package registers its own
// types from an init(), so importing a service package is enough to make its entities
// gob-encodable — no central registry, and no import fan-out for consumers.
const outFile = "gob_register_gen.go"

func main() {
	// 1. Load packages
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedTypes | packages.NeedTypesInfo,
	}
	// Loading all packages under service/... The pattern is module-relative rather than
	// cwd-relative so the generator works from the repo root and from a //go:generate directive.
	pkgs, err := packages.Load(cfg, "github.com/imunhatep/awslib/service/...")
	if err != nil {
		log.Fatal(err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	// 2. Collect types, grouped by the package that declares them
	type target struct {
		PkgName string
		Dir     string
		Types   []string
	}
	targets := make(map[string]*target) // pkg path -> target

	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.PkgPath, ".test") || pkg.Name == "main" {
			continue
		}
		if len(pkg.GoFiles) == 0 {
			continue
		}
		dir := filepath.Dir(pkg.GoFiles[0])
		targets[pkg.PkgPath] = &target{PkgName: pkg.Name, Dir: dir}

		scope := pkg.Types.Scope()
		for _, name := range scope.Names() {
			obj := scope.Lookup(name)
			if !obj.Exported() {
				continue
			}
			// Only structs
			_, ok := obj.Type().Underlying().(*types.Struct)
			if !ok {
				continue
			}

			// Filters
			if strings.HasSuffix(name, "Cached") {
				continue
			}
			if strings.HasSuffix(name, "Repository") {
				continue
			}
			if strings.HasSuffix(name, "Client") {
				continue
			}
			if strings.HasSuffix(name, "Options") {
				continue
			}
			if strings.HasSuffix(name, "Provider") {
				continue
			}
			if strings.HasPrefix(name, "Mock") {
				continue
			}

			// Exclude helper/utility structs if necessary
			// e.g. "Helper" in helper.go

			targets[pkg.PkgPath].Types = append(targets[pkg.PkgPath].Types, name)
		}
	}

	// 3. Sort for deterministic output
	paths := make([]string, 0, len(targets))
	for path := range targets {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	// 4. Emit one file per package. Types are referenced unqualified, so the generated file
	// imports nothing but encoding/gob.
	var written, removed, total int
	for _, path := range paths {
		t := targets[path]
		dst := filepath.Join(t.Dir, outFile)

		// A package that no longer declares registerable types should not keep a stale file.
		if len(t.Types) == 0 {
			if err := os.Remove(dst); err == nil {
				removed++
			} else if !os.IsNotExist(err) {
				log.Fatal(err)
			}
			continue
		}
		sort.Strings(t.Types)

		var buf bytes.Buffer
		buf.WriteString("// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.\n\n")
		buf.WriteString(fmt.Sprintf("package %s\n\n", t.PkgName))
		buf.WriteString("import \"encoding/gob\"\n\n")
		buf.WriteString("// init registers this package's types with encoding/gob so they can be\n")
		buf.WriteString("// serialized by the cache handlers. Importing this package is sufficient.\n")
		buf.WriteString("func init() {\n")
		for _, name := range t.Types {
			buf.WriteString(fmt.Sprintf("\tgob.Register(%s{})\n", name))
		}
		buf.WriteString("}\n")

		src, err := format.Source(buf.Bytes())
		if err != nil {
			log.Fatalf("format error for %s: %v", path, err)
		}
		if err := os.WriteFile(dst, src, 0644); err != nil {
			log.Fatal(err)
		}
		written++
		total += len(t.Types)
	}

	fmt.Printf("Generated %s in %d packages (%d types); removed %d stale files\n",
		outFile, written, total, removed)
}
