//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"log"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	// 1. Load packages
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo,
	}
	// Loading all packages under service/...
	pkgs, err := packages.Load(cfg, "./service/...")
	if err != nil {
		log.Fatal(err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	// 2. Collect types
	type registeredType struct {
		PkgPath  string
		PkgName  string
		TypeName string
	}
	var toRegister []registeredType

	// Track unique package names to avoid collision
	pkgNames := make(map[string]string) // path -> name

	// First pass: Collect all valid packages and assign unique names
	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.PkgPath, ".test") {
			continue
		}
		name := pkg.Name
		if name == "main" {
			continue
		}

		// Handle duplicates if any (simple approach: append number or suffix if collision,
		// but assuming awslib packages are mostly unique leaf names)
		// If collision: service/ec2 vs service/v2/ec2 -> ec2, ec2_1

		// For simplicity, we trust standard naming or just use full path alias if needed.
		// We will just use package name for now, assuming no conflicts for service packages.
		pkgNames[pkg.PkgPath] = name
	}

	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.PkgPath, ".test") {
			continue
		}

		scope := pkg.Types.Scope()
		for _, name := range scope.Names() {
			obj := scope.Lookup(name)
			if !obj.Exported() {
				continue
			}
			// Only structs
			_, ok := obj.Type().Underlying().(*types.Struct)
			if !ok {
				continue
			}

			// Filters
			if strings.HasSuffix(name, "Cached") {
				continue
			}
			if strings.HasSuffix(name, "Repository") {
				continue
			}
			if strings.HasSuffix(name, "Client") {
				continue
			}
			if strings.HasSuffix(name, "Options") {
				continue
			}
			if strings.HasSuffix(name, "Provider") {
				continue
			}
			if strings.HasPrefix(name, "Mock") {
				continue
			}

			// Exclude helper/utility structs if necessary
			// e.g. "Helper" in helper.go

			toRegister = append(toRegister, registeredType{
				PkgPath:  pkg.PkgPath,
				PkgName:  pkgNames[pkg.PkgPath],
				TypeName: name,
			})
		}
	}

	// 3. Sort for deterministic output
	sort.Slice(toRegister, func(i, j int) bool {
		if toRegister[i].PkgPath != toRegister[j].PkgPath {
			return toRegister[i].PkgPath < toRegister[j].PkgPath
		}
		return toRegister[i].TypeName < toRegister[j].TypeName
	})

	// 4. Generate code
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.\n\n")
	buf.WriteString("package awslib\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/gob\"\n\n")

	// De-duplicate imports
	imports := make(map[string]string) // path -> name
	for _, t := range toRegister {
		imports[t.PkgPath] = t.PkgName
	}
	// Sort imports
	var sortedImports []string
	for path := range imports {
		sortedImports = append(sortedImports, path)
	}
	sort.Strings(sortedImports)

	for _, path := range sortedImports {
		buf.WriteString(fmt.Sprintf("\t\"%s\"\n", path))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("func registerGeneratedServices() {\n")
	for _, t := range toRegister {
		buf.WriteString(fmt.Sprintf("\tgob.Register(%s.%s{})\n", t.PkgName, t.TypeName))
	}
	buf.WriteString("}\n")

	// 5. Write file
	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal("format error: ", err)
	}

	if err := os.WriteFile("gob_register_gen.go", src, 0644); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated gob_register_gen.go with %d types\n", len(toRegister))
}
