// Code generated by generate-cached. DO NOT EDIT.
package ec2

import (
	"fmt"

	awsec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/imunhatep/awslib/cache"
)

// Ec2RepositoryCached wraps Ec2Repository and caches results of Get*/List* calls.
type Ec2RepositoryCached struct {
	repo  *Ec2Repository
	cache *cache.DataCache
}

// WithCache returns a Ec2RepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *Ec2Repository) WithCache(dc *cache.DataCache) *Ec2RepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &Ec2RepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetInstanceTypes returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) GetInstanceTypes() ([]types.InstanceType, error) {
	cacheKey := cache.Key("GetInstanceTypes")
	var cached []types.InstanceType
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetInstanceTypes()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListInstancesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListInstancesAll() ([]Instance, error) {
	cacheKey := cache.Key("ListInstancesAll")
	var cached []Instance
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListInstancesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListInstancesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListInstancesByInput(query *awsec2.DescribeInstancesInput) ([]Instance, error) {
	cacheKey := cache.Key("ListInstancesByInput", query)
	var cached []Instance
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListInstancesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRegionByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListRegionByInput(query *awsec2.DescribeRegionsInput) ([]types.Region, error) {
	cacheKey := cache.Key("ListRegionByInput", query)
	var cached []types.Region
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRegionByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRegionsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListRegionsAll() ([]types.Region, error) {
	cacheKey := cache.Key("ListRegionsAll")
	var cached []types.Region
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRegionsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRegionsOptIn returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListRegionsOptIn() ([]types.Region, error) {
	cacheKey := cache.Key("ListRegionsOptIn")
	var cached []types.Region
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRegionsOptIn()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSnapshotsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListSnapshotsAll() ([]Snapshot, error) {
	cacheKey := cache.Key("ListSnapshotsAll")
	var cached []Snapshot
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSnapshotsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSnapshotsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListSnapshotsByInput(query *awsec2.DescribeSnapshotsInput) ([]Snapshot, error) {
	cacheKey := cache.Key("ListSnapshotsByInput", query)
	var cached []Snapshot
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSnapshotsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListVolumesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListVolumesAll() ([]Volume, error) {
	cacheKey := cache.Key("ListVolumesAll")
	var cached []Volume
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListVolumesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListVolumesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListVolumesByInput(describeInput *awsec2.DescribeVolumesInput) ([]Volume, error) {
	cacheKey := cache.Key("ListVolumesByInput", describeInput)
	var cached []Volume
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListVolumesByInput(describeInput)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListVpcsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListVpcsAll() ([]Vpc, error) {
	cacheKey := cache.Key("ListVpcsAll")
	var cached []Vpc
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListVpcsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListVpcsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Ec2RepositoryCached) ListVpcsByInput(describeInput *awsec2.DescribeVpcsInput) ([]Vpc, error) {
	cacheKey := cache.Key("ListVpcsByInput", describeInput)
	var cached []Vpc
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListVpcsByInput(describeInput)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
