// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package ec2

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(Address{})
	gob.Register(Instance{})
	gob.Register(InstanceList{})
	gob.Register(RouteTable{})
	gob.Register(SecurityGroup{})
	gob.Register(Snapshot{})
	gob.Register(Subnet{})
	gob.Register(Volume{})
	gob.Register(Vpc{})
	gob.Register(VpcEndpoint{})
}
