// Code generated by generate-cached. DO NOT EDIT.
package costexplorer

import (
	"fmt"

	awsce "github.com/aws/aws-sdk-go-v2/service/costexplorer"
	"github.com/aws/aws-sdk-go-v2/service/costexplorer/types"
	"github.com/imunhatep/awslib/cache"
	"time"
)

// CostExplorerRepositoryCached wraps CostExplorerRepository and caches results of Get*/List* calls.
type CostExplorerRepositoryCached struct {
	repo  *CostExplorerRepository
	cache *cache.DataCache
}

// WithCache returns a CostExplorerRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *CostExplorerRepository) WithCache(dc *cache.DataCache) *CostExplorerRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &CostExplorerRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetCostAndUsage returns cached results when available, otherwise delegates to the underlying repository.
func (c *CostExplorerRepositoryCached) GetCostAndUsage(query *awsce.GetCostAndUsageInput) (*CostAndUsage, error) {
	cacheKey := cache.Key("GetCostAndUsage", query)
	var cached *CostAndUsage
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCostAndUsage(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetCostAndUsageByPeriod returns cached results when available, otherwise delegates to the underlying repository.
func (c *CostExplorerRepositoryCached) GetCostAndUsageByPeriod(start time.Time, end time.Time, granularity types.Granularity, costMetrics []string, groupBy []types.GroupDefinition) (*CostAndUsage, error) {
	cacheKey := cache.Key("GetCostAndUsageByPeriod", start, end, granularity, costMetrics, groupBy)
	var cached *CostAndUsage
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCostAndUsageByPeriod(start, end, granularity, costMetrics, groupBy)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetCostAndUsageByQuery returns cached results when available, otherwise delegates to the underlying repository.
func (c *CostExplorerRepositoryCached) GetCostAndUsageByQuery(q CostQuery) (*CostAndUsage, error) {
	cacheKey := cache.Key("GetCostAndUsageByQuery", q)
	var cached *CostAndUsage
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCostAndUsageByQuery(q)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetCostForecast returns cached results when available, otherwise delegates to the underlying repository.
func (c *CostExplorerRepositoryCached) GetCostForecast(query *awsce.GetCostForecastInput) (*awsce.GetCostForecastOutput, error) {
	cacheKey := cache.Key("GetCostForecast", query)
	var cached *awsce.GetCostForecastOutput
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCostForecast(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetDimensionValues returns cached results when available, otherwise delegates to the underlying repository.
func (c *CostExplorerRepositoryCached) GetDimensionValues(query *awsce.GetDimensionValuesInput) ([]types.DimensionValuesWithAttributes, error) {
	cacheKey := cache.Key("GetDimensionValues", query)
	var cached []types.DimensionValuesWithAttributes
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetDimensionValues(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
