// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package costexplorer

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(CostAndUsage{})
	gob.Register(CostCategoryFilter{})
	gob.Register(CostQuery{})
	gob.Register(DimensionFilter{})
	gob.Register(TagFilter{})
}
