// Code generated by generate-cached. DO NOT EDIT.
package s3

import (
	"fmt"
	"hash/fnv"
	"strings"

	awss3 "github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// S3RepositoryCached wraps S3Repository and caches results of Get*/List* calls.
type S3RepositoryCached struct {
	repo  *S3Repository
	cache *cache.DataCache
}

// WithCache returns a S3RepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *S3Repository) WithCache(dc *cache.DataCache) *S3RepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &S3RepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *S3RepositoryCached) GetTags(bucket types.Bucket) ([]types.Tag, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetTags:%s", strings.Join([]string{fmt.Sprintf("%+v", bucket)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetTags(bucket)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListBucketsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *S3RepositoryCached) ListBucketsAll() ([]Bucket, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListBucketsAll"
	var cached []Bucket
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListBucketsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListBucketsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *S3RepositoryCached) ListBucketsByInput(query *awss3.ListBucketsInput) ([]Bucket, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListBucketsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Bucket
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListBucketsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
