// Code generated by generate-cached. DO NOT EDIT.
package secretmanager

import (
	"fmt"
	"hash/fnv"
	"strings"

	sm "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// SecretManagerRepositoryCached wraps SecretManagerRepository and caches results of Get*/List* calls.
type SecretManagerRepositoryCached struct {
	repo  *SecretManagerRepository
	cache *cache.DataCache
}

// WithCache returns a SecretManagerRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *SecretManagerRepository) WithCache(dc *cache.DataCache) *SecretManagerRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &SecretManagerRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListSecretsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *SecretManagerRepositoryCached) ListSecretsAll() ([]SecretEntry, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListSecretsAll"
	var cached []SecretEntry
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSecretsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSecretsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *SecretManagerRepositoryCached) ListSecretsByInput(query *sm.ListSecretsInput) ([]SecretEntry, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListSecretsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []SecretEntry
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSecretsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
