// Code generated by generate-cached. DO NOT EDIT.
package secretmanager

import (
	"fmt"

	sm "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"github.com/imunhatep/awslib/cache"
)

// SecretManagerRepositoryCached wraps SecretManagerRepository and caches results of Get*/List* calls.
type SecretManagerRepositoryCached struct {
	repo  *SecretManagerRepository
	cache *cache.DataCache
}

// WithCache returns a SecretManagerRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *SecretManagerRepository) WithCache(dc *cache.DataCache) *SecretManagerRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &SecretManagerRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListSecretsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *SecretManagerRepositoryCached) ListSecretsAll() ([]SecretEntry, error) {
	cacheKey := cache.Key("ListSecretsAll")
	var cached []SecretEntry
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSecretsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSecretsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *SecretManagerRepositoryCached) ListSecretsByInput(query *sm.ListSecretsInput) ([]SecretEntry, error) {
	cacheKey := cache.Key("ListSecretsByInput", query)
	var cached []SecretEntry
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSecretsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
