// Code generated by generate-cached. DO NOT EDIT.
package batch

import (
	"fmt"

	awsbatch "github.com/aws/aws-sdk-go-v2/service/batch"
	"github.com/imunhatep/awslib/cache"
)

// BatchRepositoryCached wraps BatchRepository and caches results of Get*/List* calls.
type BatchRepositoryCached struct {
	repo  *BatchRepository
	cache *cache.DataCache
}

// WithCache returns a BatchRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:batch".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *BatchRepository) WithCache(dc *cache.DataCache) *BatchRepositoryCached {
	ns := fmt.Sprintf("%s:%s:batch", r.client.GetAccountID(), r.client.GetRegion())
	return &BatchRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListComputeEnvironmentAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListComputeEnvironmentAll() ([]ComputeEnvironment, error) {
	cacheKey := cache.Key("ListComputeEnvironmentAll")
	var cached []ComputeEnvironment
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListComputeEnvironmentAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListComputeEnvironmentByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListComputeEnvironmentByInput(query *awsbatch.DescribeComputeEnvironmentsInput) ([]ComputeEnvironment, error) {
	cacheKey := cache.Key("ListComputeEnvironmentByInput", query)
	var cached []ComputeEnvironment
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListComputeEnvironmentByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobQueueAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListJobQueueAll() ([]JobQueue, error) {
	cacheKey := cache.Key("ListJobQueueAll")
	var cached []JobQueue
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobQueueAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobQueueByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListJobQueueByInput(query *awsbatch.DescribeJobQueuesInput) ([]JobQueue, error) {
	cacheKey := cache.Key("ListJobQueueByInput", query)
	var cached []JobQueue
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobQueueByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
