// Code generated by generate-cached. DO NOT EDIT.
package batch

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsbatch "github.com/aws/aws-sdk-go-v2/service/batch"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// BatchRepositoryCached wraps BatchRepository and caches results of Get*/List* calls.
type BatchRepositoryCached struct {
	repo  *BatchRepository
	cache *cache.DataCache
}

// WithCache returns a BatchRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *BatchRepository) WithCache(dc *cache.DataCache) *BatchRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &BatchRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListComputeEnvironmentAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListComputeEnvironmentAll() ([]ComputeEnvironment, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListComputeEnvironmentAll"
	var cached []ComputeEnvironment
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListComputeEnvironmentAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListComputeEnvironmentByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListComputeEnvironmentByInput(query *awsbatch.DescribeComputeEnvironmentsInput) ([]ComputeEnvironment, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListComputeEnvironmentByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []ComputeEnvironment
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListComputeEnvironmentByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobQueueAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListJobQueueAll() ([]JobQueue, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListJobQueueAll"
	var cached []JobQueue
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobQueueAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobQueueByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *BatchRepositoryCached) ListJobQueueByInput(query *awsbatch.DescribeJobQueuesInput) ([]JobQueue, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListJobQueueByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []JobQueue
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobQueueByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
