// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package batch

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(ComputeEnvironment{})
	gob.Register(ComputeEnvironmentList{})
	gob.Register(JobQueue{})
	gob.Register(JobQueueList{})
}
