// Code generated by generate-cached. DO NOT EDIT.
package ecs

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// EcsRepositoryCached wraps EcsRepository and caches results of Get*/List* calls.
type EcsRepositoryCached struct {
	repo  *EcsRepository
	cache *cache.DataCache
}

// WithCache returns a EcsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EcsRepository) WithCache(dc *cache.DataCache) *EcsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EcsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListClustersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListClustersAll() ([]Cluster, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListClustersAll"
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListClustersByInput(query *awsecs.ListClustersInput) ([]Cluster, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListClustersByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListServicesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListServicesAll() ([]Service, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListServicesAll"
	var cached []Service
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListServicesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListServicesByCluster returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListServicesByCluster(cluster Cluster) ([]Service, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListServicesByCluster:%s", strings.Join([]string{fmt.Sprintf("%+v", cluster)}, ":")))
	var cached []Service
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListServicesByCluster(cluster)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListServicesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListServicesByInput(query *awsecs.ListServicesInput) ([]Service, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListServicesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Service
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListServicesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
