// Code generated by generate-cached. DO NOT EDIT.
package ecs

import (
	"fmt"

	awsecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	"github.com/imunhatep/awslib/cache"
)

// EcsRepositoryCached wraps EcsRepository and caches results of Get*/List* calls.
type EcsRepositoryCached struct {
	repo  *EcsRepository
	cache *cache.DataCache
}

// WithCache returns a EcsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EcsRepository) WithCache(dc *cache.DataCache) *EcsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EcsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListClustersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListClustersAll() ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersAll")
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListClustersByInput(query *awsecs.ListClustersInput) ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersByInput", query)
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListServicesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListServicesAll() ([]Service, error) {
	cacheKey := cache.Key("ListServicesAll")
	var cached []Service
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListServicesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListServicesByCluster returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListServicesByCluster(cluster Cluster) ([]Service, error) {
	cacheKey := cache.Key("ListServicesByCluster", cluster)
	var cached []Service
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListServicesByCluster(cluster)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListServicesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EcsRepositoryCached) ListServicesByInput(query *awsecs.ListServicesInput) ([]Service, error) {
	cacheKey := cache.Key("ListServicesByInput", query)
	var cached []Service
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListServicesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
