// Code generated by generate-cached. DO NOT EDIT.
package cloudfront

import (
	"fmt"

	awscf "github.com/aws/aws-sdk-go-v2/service/cloudfront"
	cftypes "github.com/aws/aws-sdk-go-v2/service/cloudfront/types"
	"github.com/imunhatep/awslib/cache"
)

// CloudFrontRepositoryCached wraps CloudFrontRepository and caches results of Get*/List* calls.
type CloudFrontRepositoryCached struct {
	repo  *CloudFrontRepository
	cache *cache.DataCache
}

// WithCache returns a CloudFrontRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:cloudfront".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *CloudFrontRepository) WithCache(dc *cache.DataCache) *CloudFrontRepositoryCached {
	ns := fmt.Sprintf("%s:%s:cloudfront", r.client.GetAccountID(), r.client.GetRegion())
	return &CloudFrontRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetConnectionGroup returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetConnectionGroup(identifier string) (*ConnectionGroup, error) {
	cacheKey := cache.Key("GetConnectionGroup", identifier)
	var cached *ConnectionGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetConnectionGroup(identifier)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetConnectionGroupByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetConnectionGroupByInput(query *awscf.GetConnectionGroupInput) (*ConnectionGroup, error) {
	cacheKey := cache.Key("GetConnectionGroupByInput", query)
	var cached *ConnectionGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetConnectionGroupByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetConnectionGroupByRoutingEndpoint returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetConnectionGroupByRoutingEndpoint(routingEndpoint string) (*ConnectionGroup, error) {
	cacheKey := cache.Key("GetConnectionGroupByRoutingEndpoint", routingEndpoint)
	var cached *ConnectionGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetConnectionGroupByRoutingEndpoint(routingEndpoint)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetDistributionTenant returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetDistributionTenant(identifier string) (*DistributionTenant, error) {
	cacheKey := cache.Key("GetDistributionTenant", identifier)
	var cached *DistributionTenant
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetDistributionTenant(identifier)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetDistributionTenantByDomain returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetDistributionTenantByDomain(domain string) (*DistributionTenant, error) {
	cacheKey := cache.Key("GetDistributionTenantByDomain", domain)
	var cached *DistributionTenant
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetDistributionTenantByDomain(domain)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetDistributionTenantByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetDistributionTenantByInput(query *awscf.GetDistributionTenantInput) (*DistributionTenant, error) {
	cacheKey := cache.Key("GetDistributionTenantByInput", query)
	var cached *DistributionTenant
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetDistributionTenantByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetManagedCertificateDetails returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) GetManagedCertificateDetails(identifier string) (*cftypes.ManagedCertificateDetails, error) {
	cacheKey := cache.Key("GetManagedCertificateDetails", identifier)
	var cached *cftypes.ManagedCertificateDetails
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetManagedCertificateDetails(identifier)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListConnectionGroupsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListConnectionGroupsAll() ([]ConnectionGroup, error) {
	cacheKey := cache.Key("ListConnectionGroupsAll")
	var cached []ConnectionGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListConnectionGroupsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListConnectionGroupsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListConnectionGroupsByInput(query *awscf.ListConnectionGroupsInput) ([]ConnectionGroup, error) {
	cacheKey := cache.Key("ListConnectionGroupsByInput", query)
	var cached []ConnectionGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListConnectionGroupsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDistributionTenantsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListDistributionTenantsAll() ([]DistributionTenantSummary, error) {
	cacheKey := cache.Key("ListDistributionTenantsAll")
	var cached []DistributionTenantSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDistributionTenantsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDistributionTenantsByDistribution returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListDistributionTenantsByDistribution(distributionID string) ([]DistributionTenantSummary, error) {
	cacheKey := cache.Key("ListDistributionTenantsByDistribution", distributionID)
	var cached []DistributionTenantSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDistributionTenantsByDistribution(distributionID)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDistributionTenantsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListDistributionTenantsByInput(query *awscf.ListDistributionTenantsInput) ([]DistributionTenantSummary, error) {
	cacheKey := cache.Key("ListDistributionTenantsByInput", query)
	var cached []DistributionTenantSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDistributionTenantsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDistributionTenantsWithCertificatesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListDistributionTenantsWithCertificatesAll() ([]TenantCertificate, error) {
	cacheKey := cache.Key("ListDistributionTenantsWithCertificatesAll")
	var cached []TenantCertificate
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDistributionTenantsWithCertificatesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDistributionTenantsWithCertificatesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudFrontRepositoryCached) ListDistributionTenantsWithCertificatesByInput(query *awscf.ListDistributionTenantsInput) ([]TenantCertificate, error) {
	cacheKey := cache.Key("ListDistributionTenantsWithCertificatesByInput", query)
	var cached []TenantCertificate
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDistributionTenantsWithCertificatesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
