// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package cloudfront

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(ConnectionGroup{})
	gob.Register(ConnectionGroupList{})
	gob.Register(DistributionTenant{})
	gob.Register(DistributionTenantList{})
	gob.Register(DistributionTenantSummary{})
	gob.Register(DistributionTenantSummaryList{})
	gob.Register(TenantCertificate{})
}
