// Code generated by generate-cached. DO NOT EDIT.
package cloudcontrol

import (
	"fmt"

	awscloudcontrol "github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	cfg "github.com/aws/aws-sdk-go-v2/service/configservice/types"
	"github.com/imunhatep/awslib/cache"
)

// CloudControlRepositoryCached wraps CloudControlRepository and caches results of Get*/List* calls.
type CloudControlRepositoryCached struct {
	repo  *CloudControlRepository
	cache *cache.DataCache
}

// WithCache returns a CloudControlRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *CloudControlRepository) WithCache(dc *cache.DataCache) *CloudControlRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &CloudControlRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListResourcesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListResourcesByInput(query *awscloudcontrol.ListResourcesInput, detailed bool) ([]Resource, error) {
	cacheKey := cache.Key("ListResourcesByInput", query, detailed)
	var cached []Resource
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourcesByInput(query, detailed)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListResourcesByType returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListResourcesByType(resourceType cfg.ResourceType) ([]Resource, error) {
	cacheKey := cache.Key("ListResourcesByType", resourceType)
	var cached []Resource
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourcesByType(resourceType)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListResourcesByTypeDetailed returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListResourcesByTypeDetailed(resourceType cfg.ResourceType) ([]Resource, error) {
	cacheKey := cache.Key("ListResourcesByTypeDetailed", resourceType)
	var cached []Resource
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourcesByTypeDetailed(resourceType)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
