// Code generated by generate-cached. DO NOT EDIT.
package cloudcontrol

import (
	"fmt"
	"hash/fnv"
	"strings"

	cc "github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// CloudControlRepositoryCached wraps CloudControlRepository and caches results of Get*/List* calls.
type CloudControlRepositoryCached struct {
	repo  *CloudControlRepository
	cache *cache.DataCache
}

// WithCache returns a CloudControlRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *CloudControlRepository) WithCache(dc *cache.DataCache) *CloudControlRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &CloudControlRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListBucketsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListBucketsAll() ([]Bucket, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListBucketsAll"
	var cached []Bucket
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListBucketsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListBucketsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListBucketsByInput(query *cc.ListResourcesInput) ([]Bucket, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListBucketsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Bucket
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListBucketsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListInstancesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListInstancesAll() ([]Instance, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListInstancesAll"
	var cached []Instance
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListInstancesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListInstancesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListInstancesByInput(query *cc.ListResourcesInput) ([]Instance, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListInstancesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Instance
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListInstancesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListVolumesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudControlRepositoryCached) ListVolumesAll() ([]Volume, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListVolumesAll"
	var cached []Volume
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListVolumesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
