// Code generated by generate-cached. DO NOT EDIT.
package efs

import (
	"fmt"

	awsefs "github.com/aws/aws-sdk-go-v2/service/efs"
	"github.com/imunhatep/awslib/cache"
)

// EfsRepositoryCached wraps EfsRepository and caches results of Get*/List* calls.
type EfsRepositoryCached struct {
	repo  *EfsRepository
	cache *cache.DataCache
}

// WithCache returns a EfsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:efs".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *EfsRepository) WithCache(dc *cache.DataCache) *EfsRepositoryCached {
	ns := fmt.Sprintf("%s:%s:efs", r.client.GetAccountID(), r.client.GetRegion())
	return &EfsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListFileSystemsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EfsRepositoryCached) ListFileSystemsAll() ([]FileSystem, error) {
	cacheKey := cache.Key("ListFileSystemsAll")
	var cached []FileSystem
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFileSystemsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListFileSystemsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EfsRepositoryCached) ListFileSystemsByInput(query *awsefs.DescribeFileSystemsInput) ([]FileSystem, error) {
	cacheKey := cache.Key("ListFileSystemsByInput", query)
	var cached []FileSystem
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFileSystemsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
