// Code generated by generate-cached. DO NOT EDIT.
package efs

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsefs "github.com/aws/aws-sdk-go-v2/service/efs"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// EfsRepositoryCached wraps EfsRepository and caches results of Get*/List* calls.
type EfsRepositoryCached struct {
	repo  *EfsRepository
	cache *cache.DataCache
}

// WithCache returns a EfsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EfsRepository) WithCache(dc *cache.DataCache) *EfsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EfsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListFileSystemsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EfsRepositoryCached) ListFileSystemsAll() ([]FileSystem, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListFileSystemsAll"
	var cached []FileSystem
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFileSystemsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListFileSystemsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EfsRepositoryCached) ListFileSystemsByInput(query *awsefs.DescribeFileSystemsInput) ([]FileSystem, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListFileSystemsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []FileSystem
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFileSystemsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
