// Code generated by generate-cached. DO NOT EDIT.
package athena

import (
	"fmt"

	"github.com/imunhatep/awslib/cache"
)

// AthenaRepositoryCached wraps AthenaRepository and caches results of Get*/List* calls.
type AthenaRepositoryCached struct {
	repo  *AthenaRepository
	cache *cache.DataCache
}

// WithCache returns a AthenaRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *AthenaRepository) WithCache(dc *cache.DataCache) *AthenaRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &AthenaRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListDataCatalogsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *AthenaRepositoryCached) ListDataCatalogsAll() ([]DataCatalog, error) {
	cacheKey := cache.Key("ListDataCatalogsAll")
	var cached []DataCatalog
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDataCatalogsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListWorkGroupAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *AthenaRepositoryCached) ListWorkGroupAll() ([]WorkGroup, error) {
	cacheKey := cache.Key("ListWorkGroupAll")
	var cached []WorkGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListWorkGroupAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
