// Code generated by generate-cached. DO NOT EDIT.
package autoscaling

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsautoscaling "github.com/aws/aws-sdk-go-v2/service/autoscaling"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// AutoscalingRepositoryCached wraps AutoscalingRepository and caches results of Get*/List* calls.
type AutoscalingRepositoryCached struct {
	repo  *AutoscalingRepository
	cache *cache.DataCache
}

// WithCache returns a AutoscalingRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *AutoscalingRepository) WithCache(dc *cache.DataCache) *AutoscalingRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &AutoscalingRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListAutoScalingGroups returns cached results when available, otherwise delegates to the underlying repository.
func (c *AutoscalingRepositoryCached) ListAutoScalingGroups(query *awsautoscaling.DescribeAutoScalingGroupsInput) ([]AutoScalingGroup, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAutoScalingGroups:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []AutoScalingGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAutoScalingGroups(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAutoScalingGroupsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *AutoscalingRepositoryCached) ListAutoScalingGroupsAll() ([]AutoScalingGroup, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListAutoScalingGroupsAll"
	var cached []AutoScalingGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAutoScalingGroupsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
