// Code generated by generate-cached. DO NOT EDIT.
package autoscaling

import (
	"fmt"

	awsautoscaling "github.com/aws/aws-sdk-go-v2/service/autoscaling"
	"github.com/imunhatep/awslib/cache"
)

// AutoscalingRepositoryCached wraps AutoscalingRepository and caches results of Get*/List* calls.
type AutoscalingRepositoryCached struct {
	repo  *AutoscalingRepository
	cache *cache.DataCache
}

// WithCache returns a AutoscalingRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:autoscaling".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *AutoscalingRepository) WithCache(dc *cache.DataCache) *AutoscalingRepositoryCached {
	ns := fmt.Sprintf("%s:%s:autoscaling", r.client.GetAccountID(), r.client.GetRegion())
	return &AutoscalingRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListAutoScalingGroups returns cached results when available, otherwise delegates to the underlying repository.
func (c *AutoscalingRepositoryCached) ListAutoScalingGroups(query *awsautoscaling.DescribeAutoScalingGroupsInput) ([]AutoScalingGroup, error) {
	cacheKey := cache.Key("ListAutoScalingGroups", query)
	var cached []AutoScalingGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAutoScalingGroups(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAutoScalingGroupsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *AutoscalingRepositoryCached) ListAutoScalingGroupsAll() ([]AutoScalingGroup, error) {
	cacheKey := cache.Key("ListAutoScalingGroupsAll")
	var cached []AutoScalingGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAutoScalingGroupsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
