// Code generated by generate-cached. DO NOT EDIT.
package iam

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsiam "github.com/aws/aws-sdk-go-v2/service/iam"
	"github.com/aws/aws-sdk-go-v2/service/iam/types"
	"github.com/imunhatep/awslib/cache"
	ptypes "github.com/imunhatep/awslib/provider/types"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// IamRepositoryCached wraps IamRepository and caches results of Get*/List* calls.
type IamRepositoryCached struct {
	repo  *IamRepository
	cache *cache.DataCache
}

// WithCache returns a IamRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *IamRepository) WithCache(dc *cache.DataCache) *IamRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &IamRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListAssumedRoleArn returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAssumedRoleArn(policyVersion PolicyVersion) []ptypes.RoleArn {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAssumedRoleArn:%s", strings.Join([]string{fmt.Sprintf("%+v", policyVersion)}, ":")))
	var cached []ptypes.RoleArn
	if c.cache.Read(cacheKey, &cached) {
		return cached
	}
	r0 := c.repo.ListAssumedRoleArn(policyVersion)
	return r0
}

// ListAttachedRolePoliciesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePoliciesByInput(query *awsiam.ListAttachedRolePoliciesInput) ([]Policy, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAttachedRolePoliciesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePoliciesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePoliciesByRole returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePoliciesByRole(role Role) ([]Policy, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAttachedRolePoliciesByRole:%s", strings.Join([]string{fmt.Sprintf("%+v", role)}, ":")))
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePoliciesByRole(role)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePolicyVersionsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePolicyVersionsByInput(query *awsiam.ListAttachedRolePoliciesInput) ([]PolicyVersion, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAttachedRolePolicyVersionsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []PolicyVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePolicyVersionsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePolicyVersionsByRole returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePolicyVersionsByRole(role Role) ([]PolicyVersion, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAttachedRolePolicyVersionsByRole:%s", strings.Join([]string{fmt.Sprintf("%+v", role)}, ":")))
	var cached []PolicyVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePolicyVersionsByRole(role)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePolicyVersionsByRoleName returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePolicyVersionsByRoleName(name string) ([]PolicyVersion, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListAttachedRolePolicyVersionsByRoleName:%s", strings.Join([]string{fmt.Sprintf("%+v", name)}, ":")))
	var cached []PolicyVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePolicyVersionsByRoleName(name)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListPoliciesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListPoliciesAll() ([]Policy, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListPoliciesAll"
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListPoliciesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListPoliciesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListPoliciesByInput(query *awsiam.ListPoliciesInput) ([]Policy, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListPoliciesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListPoliciesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListPolicyTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListPolicyTags(policy types.Policy) ([]types.Tag, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListPolicyTags:%s", strings.Join([]string{fmt.Sprintf("%+v", policy)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListPolicyTags(policy)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRoleTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListRoleTags(role types.Role) ([]types.Tag, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListRoleTags:%s", strings.Join([]string{fmt.Sprintf("%+v", role)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRoleTags(role)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRolesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListRolesAll() ([]Role, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListRolesAll"
	var cached []Role
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRolesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRolesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListRolesByInput(query *awsiam.ListRolesInput) ([]Role, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListRolesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Role
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRolesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListUserTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListUserTags(user types.User) ([]types.Tag, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListUserTags:%s", strings.Join([]string{fmt.Sprintf("%+v", user)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListUserTags(user)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListUsersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListUsersAll() ([]User, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListUsersAll"
	var cached []User
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListUsersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListUsersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListUsersByInput(query *awsiam.ListUsersInput) ([]User, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListUsersByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []User
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListUsersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
