// Code generated by generate-cached. DO NOT EDIT.
package iam

import (
	"fmt"

	awsiam "github.com/aws/aws-sdk-go-v2/service/iam"
	"github.com/aws/aws-sdk-go-v2/service/iam/types"
	"github.com/imunhatep/awslib/cache"
	ptypes "github.com/imunhatep/awslib/provider/types"
)

// IamRepositoryCached wraps IamRepository and caches results of Get*/List* calls.
type IamRepositoryCached struct {
	repo  *IamRepository
	cache *cache.DataCache
}

// WithCache returns a IamRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:iam".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *IamRepository) WithCache(dc *cache.DataCache) *IamRepositoryCached {
	ns := fmt.Sprintf("%s:%s:iam", r.client.GetAccountID(), r.client.GetRegion())
	return &IamRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListAssumedRoleArn returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAssumedRoleArn(policyVersion PolicyVersion) []ptypes.RoleArn {
	cacheKey := cache.Key("ListAssumedRoleArn", policyVersion)
	var cached []ptypes.RoleArn
	if c.cache.Read(cacheKey, &cached) {
		return cached
	}
	r0 := c.repo.ListAssumedRoleArn(policyVersion)
	return r0
}

// ListAttachedRolePoliciesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePoliciesByInput(query *awsiam.ListAttachedRolePoliciesInput) ([]Policy, error) {
	cacheKey := cache.Key("ListAttachedRolePoliciesByInput", query)
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePoliciesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePoliciesByRole returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePoliciesByRole(role Role) ([]Policy, error) {
	cacheKey := cache.Key("ListAttachedRolePoliciesByRole", role)
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePoliciesByRole(role)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePolicyVersionsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePolicyVersionsByInput(query *awsiam.ListAttachedRolePoliciesInput) ([]PolicyVersion, error) {
	cacheKey := cache.Key("ListAttachedRolePolicyVersionsByInput", query)
	var cached []PolicyVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePolicyVersionsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePolicyVersionsByRole returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePolicyVersionsByRole(role Role) ([]PolicyVersion, error) {
	cacheKey := cache.Key("ListAttachedRolePolicyVersionsByRole", role)
	var cached []PolicyVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePolicyVersionsByRole(role)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListAttachedRolePolicyVersionsByRoleName returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListAttachedRolePolicyVersionsByRoleName(name string) ([]PolicyVersion, error) {
	cacheKey := cache.Key("ListAttachedRolePolicyVersionsByRoleName", name)
	var cached []PolicyVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListAttachedRolePolicyVersionsByRoleName(name)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListPoliciesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListPoliciesAll() ([]Policy, error) {
	cacheKey := cache.Key("ListPoliciesAll")
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListPoliciesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListPoliciesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListPoliciesByInput(query *awsiam.ListPoliciesInput) ([]Policy, error) {
	cacheKey := cache.Key("ListPoliciesByInput", query)
	var cached []Policy
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListPoliciesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListPolicyTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListPolicyTags(policy types.Policy) ([]types.Tag, error) {
	cacheKey := cache.Key("ListPolicyTags", policy)
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListPolicyTags(policy)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRoleTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListRoleTags(role types.Role) ([]types.Tag, error) {
	cacheKey := cache.Key("ListRoleTags", role)
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRoleTags(role)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRolesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListRolesAll() ([]Role, error) {
	cacheKey := cache.Key("ListRolesAll")
	var cached []Role
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRolesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListRolesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListRolesByInput(query *awsiam.ListRolesInput) ([]Role, error) {
	cacheKey := cache.Key("ListRolesByInput", query)
	var cached []Role
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListRolesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListUserTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListUserTags(user types.User) ([]types.Tag, error) {
	cacheKey := cache.Key("ListUserTags", user)
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListUserTags(user)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListUsersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListUsersAll() ([]User, error) {
	cacheKey := cache.Key("ListUsersAll")
	var cached []User
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListUsersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListUsersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *IamRepositoryCached) ListUsersByInput(query *awsiam.ListUsersInput) ([]User, error) {
	cacheKey := cache.Key("ListUsersByInput", query)
	var cached []User
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListUsersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
