// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package iam

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(Policy{})
	gob.Register(PolicyDocument{})
	gob.Register(PolicyList{})
	gob.Register(PolicyVersion{})
	gob.Register(Role{})
	gob.Register(RoleList{})
	gob.Register(Statement{})
	gob.Register(User{})
	gob.Register(UserList{})
}
