// Package all provides a convenience option to enable all AWS services
// WARNING: Using this defeats the purpose of selective compilation and will result in large binaries
package all

import (
	"github.com/imunhatep/awslib/provider/v3"
	"github.com/imunhatep/awslib/provider/v3/clients/accessanalyzer"
	"github.com/imunhatep/awslib/provider/v3/clients/acm"
	"github.com/imunhatep/awslib/provider/v3/clients/apigateway"
	"github.com/imunhatep/awslib/provider/v3/clients/athena"
	"github.com/imunhatep/awslib/provider/v3/clients/autoscaling"
	"github.com/imunhatep/awslib/provider/v3/clients/batch"
	"github.com/imunhatep/awslib/provider/v3/clients/cloudcontrol"
	"github.com/imunhatep/awslib/provider/v3/clients/cloudformation"
	"github.com/imunhatep/awslib/provider/v3/clients/cloudtrail"
	"github.com/imunhatep/awslib/provider/v3/clients/cloudwatch"
	"github.com/imunhatep/awslib/provider/v3/clients/cloudwatchlogs"
	"github.com/imunhatep/awslib/provider/v3/clients/configservice"
	"github.com/imunhatep/awslib/provider/v3/clients/costexplorer"
	"github.com/imunhatep/awslib/provider/v3/clients/dynamodb"
	"github.com/imunhatep/awslib/provider/v3/clients/ec2"
	"github.com/imunhatep/awslib/provider/v3/clients/ecs"
	"github.com/imunhatep/awslib/provider/v3/clients/efs"
	"github.com/imunhatep/awslib/provider/v3/clients/eks"
	"github.com/imunhatep/awslib/provider/v3/clients/elasticache"
	"github.com/imunhatep/awslib/provider/v3/clients/elasticloadbalancingv2"
	"github.com/imunhatep/awslib/provider/v3/clients/emr"
	"github.com/imunhatep/awslib/provider/v3/clients/emrserverless"
	"github.com/imunhatep/awslib/provider/v3/clients/glue"
	"github.com/imunhatep/awslib/provider/v3/clients/health"
	"github.com/imunhatep/awslib/provider/v3/clients/iam"
	"github.com/imunhatep/awslib/provider/v3/clients/lambda"
	"github.com/imunhatep/awslib/provider/v3/clients/pricing"
	"github.com/imunhatep/awslib/provider/v3/clients/rds"
	"github.com/imunhatep/awslib/provider/v3/clients/route53"
	"github.com/imunhatep/awslib/provider/v3/clients/s3"
	"github.com/imunhatep/awslib/provider/v3/clients/s3control"
	"github.com/imunhatep/awslib/provider/v3/clients/s3outposts"
	"github.com/imunhatep/awslib/provider/v3/clients/savingsplans"
	"github.com/imunhatep/awslib/provider/v3/clients/secretsmanager"
	"github.com/imunhatep/awslib/provider/v3/clients/securityhub"
	"github.com/imunhatep/awslib/provider/v3/clients/servicecatalog"
	"github.com/imunhatep/awslib/provider/v3/clients/servicediscovery"
	"github.com/imunhatep/awslib/provider/v3/clients/servicequotas"
	"github.com/imunhatep/awslib/provider/v3/clients/ses"
	"github.com/imunhatep/awslib/provider/v3/clients/sfn"
	"github.com/imunhatep/awslib/provider/v3/clients/shield"
	"github.com/imunhatep/awslib/provider/v3/clients/signer"
	"github.com/imunhatep/awslib/provider/v3/clients/sns"
	"github.com/imunhatep/awslib/provider/v3/clients/sqs"
	"github.com/imunhatep/awslib/provider/v3/clients/ssm"
	"github.com/imunhatep/awslib/provider/v3/clients/storagegateway"
	"github.com/imunhatep/awslib/provider/v3/clients/swf"
	"github.com/imunhatep/awslib/provider/v3/clients/synthetics"
	"github.com/imunhatep/awslib/provider/v3/clients/timestreamwrite"
	"github.com/imunhatep/awslib/provider/v3/clients/transfer"
	"github.com/imunhatep/awslib/provider/v3/clients/waf"
	"github.com/imunhatep/awslib/provider/v3/clients/wafregional"
	"github.com/imunhatep/awslib/provider/v3/clients/wafv2"
)

// WithAll enables all AWS services
// WARNING: This will result in large binaries (~85MB). Only use for testing or when you truly need all services.
// For production, import only the specific service options you need.
func WithAll() v3.ClientOption {
	return v3.CombineOptions(
		accessanalyzer.WithAccessAnalyzer(),
		acm.WithACM(),
		apigateway.WithAPIGateway(),
		athena.WithAthena(),
		autoscaling.WithAutoScaling(),
		batch.WithBatch(),
		cloudcontrol.WithCloudControl(),
		cloudformation.WithCloudFormation(),
		cloudtrail.WithCloudTrail(),
		cloudwatch.WithCloudWatch(),
		cloudwatchlogs.WithCloudWatchLogs(),
		configservice.WithConfigService(),
		costexplorer.WithCostExplorer(),
		dynamodb.WithDynamoDB(),
		ec2.WithEC2(),
		ecs.WithECS(),
		efs.WithEFS(),
		eks.WithEKS(),
		elasticache.WithElastiCache(),
		elasticloadbalancingv2.WithElasticLoadBalancingV2(),
		emr.WithEMR(),
		emrserverless.WithEMRServerless(),
		glue.WithGlue(),
		health.WithHealth(),
		iam.WithIAM(),
		lambda.WithLambda(),
		pricing.WithPricing(),
		rds.WithRDS(),
		route53.WithRoute53(),
		s3.WithS3(),
		s3control.WithS3Control(),
		s3outposts.WithS3Outposts(),
		savingsplans.WithSavingsPlans(),
		secretsmanager.WithSecretsManager(),
		securityhub.WithSecurityHub(),
		servicecatalog.WithServiceCatalog(),
		servicediscovery.WithServiceDiscovery(),
		servicequotas.WithServiceQuotas(),
		ses.WithSES(),
		sfn.WithStepFunctions(),
		shield.WithShield(),
		signer.WithSigner(),
		sns.WithSNS(),
		sqs.WithSQS(),
		ssm.WithSSM(),
		storagegateway.WithStorageGateway(),
		swf.WithSWF(),
		synthetics.WithSynthetics(),
		timestreamwrite.WithTimestreamWrite(),
		transfer.WithTransfer(),
		waf.WithWAF(),
		wafregional.WithWAFRegional(),
		wafv2.WithWAFv2(),
	)
}
