// Code generated by generate-cached. DO NOT EDIT.
package sqs

import (
	"fmt"

	awssqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/imunhatep/awslib/cache"
)

// SqsRepositoryCached wraps SqsRepository and caches results of Get*/List* calls.
type SqsRepositoryCached struct {
	repo  *SqsRepository
	cache *cache.DataCache
}

// WithCache returns a SqsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *SqsRepository) WithCache(dc *cache.DataCache) *SqsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &SqsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetQueueTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *SqsRepositoryCached) GetQueueTags(queueUrl string) (map[string]string, error) {
	cacheKey := cache.Key("GetQueueTags", queueUrl)
	var cached map[string]string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetQueueTags(queueUrl)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListQueuesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *SqsRepositoryCached) ListQueuesAll() ([]Queue, error) {
	cacheKey := cache.Key("ListQueuesAll")
	var cached []Queue
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListQueuesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListQueuesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *SqsRepositoryCached) ListQueuesByInput(query *awssqs.ListQueuesInput) ([]Queue, error) {
	cacheKey := cache.Key("ListQueuesByInput", query)
	var cached []Queue
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListQueuesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
