// Code generated by generate-cached. DO NOT EDIT.
package glue

import (
	"fmt"

	awsglue "github.com/aws/aws-sdk-go-v2/service/glue"
	"github.com/imunhatep/awslib/cache"
)

// GlueRepositoryCached wraps GlueRepository and caches results of Get*/List* calls.
type GlueRepositoryCached struct {
	repo  *GlueRepository
	cache *cache.DataCache
}

// WithCache returns a GlueRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *GlueRepository) WithCache(dc *cache.DataCache) *GlueRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &GlueRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListDatabaseAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *GlueRepositoryCached) ListDatabaseAll() ([]Database, error) {
	cacheKey := cache.Key("ListDatabaseAll")
	var cached []Database
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDatabaseAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDatabaseByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *GlueRepositoryCached) ListDatabaseByInput(query *awsglue.GetDatabasesInput) ([]Database, error) {
	cacheKey := cache.Key("ListDatabaseByInput", query)
	var cached []Database
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDatabaseByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *GlueRepositoryCached) ListJobsAll() ([]Job, error) {
	cacheKey := cache.Key("ListJobsAll")
	var cached []Job
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListJobsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *GlueRepositoryCached) ListJobsByInput(query *awsglue.GetJobsInput) ([]Job, error) {
	cacheKey := cache.Key("ListJobsByInput", query)
	var cached []Job
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListJobsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTablesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *GlueRepositoryCached) ListTablesAll() ([]Table, error) {
	cacheKey := cache.Key("ListTablesAll")
	var cached []Table
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTablesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTablesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *GlueRepositoryCached) ListTablesByInput(query *awsglue.GetTablesInput) ([]Table, error) {
	cacheKey := cache.Key("ListTablesByInput", query)
	var cached []Table
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTablesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
