// Code generated by generate-cached. DO NOT EDIT.
package lambda

import (
	"fmt"

	awslambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	types2 "github.com/aws/aws-sdk-go-v2/service/lambda/types"
	"github.com/imunhatep/awslib/cache"
)

// LambdaRepositoryCached wraps LambdaRepository and caches results of Get*/List* calls.
type LambdaRepositoryCached struct {
	repo  *LambdaRepository
	cache *cache.DataCache
}

// WithCache returns a LambdaRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *LambdaRepository) WithCache(dc *cache.DataCache) *LambdaRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &LambdaRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListFunctionTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *LambdaRepositoryCached) ListFunctionTags(fn types2.FunctionConfiguration) (map[string]string, error) {
	cacheKey := cache.Key("ListFunctionTags", fn)
	var cached map[string]string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFunctionTags(fn)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListFunctionsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *LambdaRepositoryCached) ListFunctionsAll() ([]Function, error) {
	cacheKey := cache.Key("ListFunctionsAll")
	var cached []Function
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFunctionsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListFunctionsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *LambdaRepositoryCached) ListFunctionsByInput(query *awslambda.ListFunctionsInput) ([]Function, error) {
	cacheKey := cache.Key("ListFunctionsByInput", query)
	var cached []Function
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFunctionsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
