// Code generated by generate-cached. DO NOT EDIT.
package lambda

import (
	"fmt"
	"hash/fnv"
	"strings"

	awslambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	types2 "github.com/aws/aws-sdk-go-v2/service/lambda/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// LambdaRepositoryCached wraps LambdaRepository and caches results of Get*/List* calls.
type LambdaRepositoryCached struct {
	repo  *LambdaRepository
	cache *cache.DataCache
}

// WithCache returns a LambdaRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *LambdaRepository) WithCache(dc *cache.DataCache) *LambdaRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &LambdaRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListFunctionTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *LambdaRepositoryCached) ListFunctionTags(fn types2.FunctionConfiguration) (map[string]string, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListFunctionTags:%s", strings.Join([]string{fmt.Sprintf("%+v", fn)}, ":")))
	var cached map[string]string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFunctionTags(fn)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListFunctionsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *LambdaRepositoryCached) ListFunctionsAll() ([]Function, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListFunctionsAll"
	var cached []Function
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFunctionsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListFunctionsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *LambdaRepositoryCached) ListFunctionsByInput(query *awslambda.ListFunctionsInput) ([]Function, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListFunctionsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Function
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListFunctionsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
