// Code generated by generate-cached. DO NOT EDIT.
package elb

import (
	"fmt"

	awselbv2 "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	"github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2/types"
	"github.com/imunhatep/awslib/cache"
)

// LoadBalancerRepositoryCached wraps LoadBalancerRepository and caches results of Get*/List* calls.
type LoadBalancerRepositoryCached struct {
	repo  *LoadBalancerRepository
	cache *cache.DataCache
}

// WithCache returns a LoadBalancerRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *LoadBalancerRepository) WithCache(dc *cache.DataCache) *LoadBalancerRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &LoadBalancerRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetLoadBalancerTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *LoadBalancerRepositoryCached) GetLoadBalancerTags(lb types.LoadBalancer) ([]types.Tag, error) {
	cacheKey := cache.Key("GetLoadBalancerTags", lb)
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetLoadBalancerTags(lb)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListLoadBalancersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *LoadBalancerRepositoryCached) ListLoadBalancersAll() ([]LoadBalancer, error) {
	cacheKey := cache.Key("ListLoadBalancersAll")
	var cached []LoadBalancer
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListLoadBalancersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListLoadBalancersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *LoadBalancerRepositoryCached) ListLoadBalancersByInput(query *awselbv2.DescribeLoadBalancersInput) ([]LoadBalancer, error) {
	cacheKey := cache.Key("ListLoadBalancersByInput", query)
	var cached []LoadBalancer
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListLoadBalancersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
