// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package elb

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(LoadBalancer{})
	gob.Register(LoadBalancerList{})
}
