// Code generated by generate-cached. DO NOT EDIT.
package route53

import (
	"fmt"

	awsr53 "github.com/aws/aws-sdk-go-v2/service/route53"
	"github.com/aws/aws-sdk-go-v2/service/route53/types"
	awsdomains "github.com/aws/aws-sdk-go-v2/service/route53domains"
	domtypes "github.com/aws/aws-sdk-go-v2/service/route53domains/types"
	"github.com/imunhatep/awslib/cache"
)

// Route53RepositoryCached wraps Route53Repository and caches results of Get*/List* calls.
type Route53RepositoryCached struct {
	repo  *Route53Repository
	cache *cache.DataCache
}

// WithCache returns a Route53RepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:route53".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *Route53Repository) WithCache(dc *cache.DataCache) *Route53RepositoryCached {
	ns := fmt.Sprintf("%s:%s:route53", r.client.GetAccountID(), r.client.GetRegion())
	return &Route53RepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetDomainByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetDomainByInput(query *awsdomains.GetDomainDetailInput) (*Domain, error) {
	cacheKey := cache.Key("GetDomainByInput", query)
	var cached *Domain
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetDomainByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetDomainTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetDomainTags(domainName string) []domtypes.Tag {
	cacheKey := cache.Key("GetDomainTags", domainName)
	var cached []domtypes.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached
	}
	r0 := c.repo.GetDomainTags(domainName)
	return r0
}

// GetHostedZoneByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetHostedZoneByInput(query *awsr53.GetHostedZoneInput) (*HostedZone, error) {
	cacheKey := cache.Key("GetHostedZoneByInput", query)
	var cached *HostedZone
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetHostedZoneByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetHostedZoneTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetHostedZoneTags(hostedZone types.HostedZone) []types.Tag {
	cacheKey := cache.Key("GetHostedZoneTags", hostedZone)
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached
	}
	r0 := c.repo.GetHostedZoneTags(hostedZone)
	return r0
}

// GetOperationDetail returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetOperationDetail(input *awsdomains.GetOperationDetailInput) (*awsdomains.GetOperationDetailOutput, error) {
	cacheKey := cache.Key("GetOperationDetail", input)
	var cached *awsdomains.GetOperationDetailOutput
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetOperationDetail(input)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDomainsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListDomainsAll() ([]DomainSummary, error) {
	cacheKey := cache.Key("ListDomainsAll")
	var cached []DomainSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDomainsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDomainsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListDomainsByInput(query *awsdomains.ListDomainsInput) ([]DomainSummary, error) {
	cacheKey := cache.Key("ListDomainsByInput", query)
	var cached []DomainSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDomainsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDomainsDetailsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListDomainsDetailsByInput(query *awsdomains.ListDomainsInput) ([]Domain, error) {
	cacheKey := cache.Key("ListDomainsDetailsByInput", query)
	var cached []Domain
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDomainsDetailsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListHostedZonesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListHostedZonesAll() ([]HostedZone, error) {
	cacheKey := cache.Key("ListHostedZonesAll")
	var cached []HostedZone
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListHostedZonesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListHostedZonesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListHostedZonesByInput(query *awsr53.ListHostedZonesInput) ([]HostedZone, error) {
	cacheKey := cache.Key("ListHostedZonesByInput", query)
	var cached []HostedZone
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListHostedZonesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListOperations returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListOperations(opTypes []domtypes.OperationType, statuses []domtypes.OperationStatus) ([]OperationInfo, error) {
	cacheKey := cache.Key("ListOperations", opTypes, statuses)
	var cached []OperationInfo
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListOperations(opTypes, statuses)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListResourceRecords returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListResourceRecords(hostedZone HostedZone) ([]ResourceRecord, error) {
	cacheKey := cache.Key("ListResourceRecords", hostedZone)
	var cached []ResourceRecord
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourceRecords(hostedZone)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListResourceRecordsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListResourceRecordsByInput(query *awsr53.ListResourceRecordSetsInput) ([]ResourceRecord, error) {
	cacheKey := cache.Key("ListResourceRecordsByInput", query)
	var cached []ResourceRecord
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourceRecordsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
