// Code generated by generate-cached. DO NOT EDIT.
package route53

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsr53 "github.com/aws/aws-sdk-go-v2/service/route53"
	"github.com/aws/aws-sdk-go-v2/service/route53/types"
	awsdomains "github.com/aws/aws-sdk-go-v2/service/route53domains"
	domtypes "github.com/aws/aws-sdk-go-v2/service/route53domains/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// Route53RepositoryCached wraps Route53Repository and caches results of Get*/List* calls.
type Route53RepositoryCached struct {
	repo  *Route53Repository
	cache *cache.DataCache
}

// WithCache returns a Route53RepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *Route53Repository) WithCache(dc *cache.DataCache) *Route53RepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &Route53RepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetDomainByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetDomainByInput(query *awsdomains.GetDomainDetailInput) (*Domain, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetDomainByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached *Domain
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetDomainByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetDomainTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetDomainTags(domainName string) []domtypes.Tag {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetDomainTags:%s", strings.Join([]string{fmt.Sprintf("%+v", domainName)}, ":")))
	var cached []domtypes.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached
	}
	r0 := c.repo.GetDomainTags(domainName)
	return r0
}

// GetHostedZoneByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetHostedZoneByInput(query *awsr53.GetHostedZoneInput) (*HostedZone, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetHostedZoneByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached *HostedZone
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetHostedZoneByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetHostedZoneTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) GetHostedZoneTags(hostedZone types.HostedZone) []types.Tag {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetHostedZoneTags:%s", strings.Join([]string{fmt.Sprintf("%+v", hostedZone)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached
	}
	r0 := c.repo.GetHostedZoneTags(hostedZone)
	return r0
}

// ListDomainsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListDomainsAll() ([]DomainSummary, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListDomainsAll"
	var cached []DomainSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDomainsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDomainsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListDomainsByInput(query *awsdomains.ListDomainsInput) ([]DomainSummary, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListDomainsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []DomainSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDomainsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDomainsDetailsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListDomainsDetailsByInput(query *awsdomains.ListDomainsInput) ([]Domain, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListDomainsDetailsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Domain
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDomainsDetailsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListHostedZonesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListHostedZonesAll() ([]HostedZone, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListHostedZonesAll"
	var cached []HostedZone
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListHostedZonesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListHostedZonesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListHostedZonesByInput(query *awsr53.ListHostedZonesInput) ([]HostedZone, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListHostedZonesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []HostedZone
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListHostedZonesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListResourceRecords returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListResourceRecords(hostedZone HostedZone) ([]ResourceRecord, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListResourceRecords:%s", strings.Join([]string{fmt.Sprintf("%+v", hostedZone)}, ":")))
	var cached []ResourceRecord
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourceRecords(hostedZone)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListResourceRecordsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *Route53RepositoryCached) ListResourceRecordsByInput(query *awsr53.ListResourceRecordSetsInput) ([]ResourceRecord, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListResourceRecordsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []ResourceRecord
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListResourceRecordsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
