// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package route53

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(Domain{})
	gob.Register(DomainList{})
	gob.Register(DomainSummary{})
	gob.Register(DomainSummaryList{})
	gob.Register(HostedZone{})
	gob.Register(HostedZoneList{})
	gob.Register(OperationInfo{})
	gob.Register(ResourceRecord{})
	gob.Register(ResourceRecordList{})
}
