// Code generated by generate-cached. DO NOT EDIT.
package health

import (
	"fmt"

	awshealth "github.com/aws/aws-sdk-go-v2/service/health"
	"github.com/aws/aws-sdk-go-v2/service/health/types"
	"github.com/imunhatep/awslib/cache"
)

// HealthRepositoryCached wraps HealthRepository and caches results of Get*/List* calls.
type HealthRepositoryCached struct {
	repo  *HealthRepository
	cache *cache.DataCache
}

// WithCache returns a HealthRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *HealthRepository) WithCache(dc *cache.DataCache) *HealthRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &HealthRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListEventsDetailsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *HealthRepositoryCached) ListEventsDetailsByInput(query *awshealth.DescribeEventsInput) ([]types.EventDetails, error) {
	cacheKey := cache.Key("ListEventsDetailsByInput", query)
	var cached []types.EventDetails
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListEventsDetailsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
