// Code generated by generate-cached. DO NOT EDIT.
package health

import (
	"fmt"
	"hash/fnv"
	"strings"

	awshealth "github.com/aws/aws-sdk-go-v2/service/health"
	"github.com/aws/aws-sdk-go-v2/service/health/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// HealthRepositoryCached wraps HealthRepository and caches results of Get*/List* calls.
type HealthRepositoryCached struct {
	repo  *HealthRepository
	cache *cache.DataCache
}

// WithCache returns a HealthRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *HealthRepository) WithCache(dc *cache.DataCache) *HealthRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &HealthRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListEventsDetailsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *HealthRepositoryCached) ListEventsDetailsByInput(query *awshealth.DescribeEventsInput) ([]types.EventDetails, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListEventsDetailsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []types.EventDetails
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListEventsDetailsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
