// Code generated by generate-cached. DO NOT EDIT.
package acm

import (
	"fmt"

	awsacm "github.com/aws/aws-sdk-go-v2/service/acm"
	"github.com/imunhatep/awslib/cache"
)

// AcmRepositoryCached wraps AcmRepository and caches results of Get*/List* calls.
type AcmRepositoryCached struct {
	repo  *AcmRepository
	cache *cache.DataCache
}

// WithCache returns a AcmRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:acm".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *AcmRepository) WithCache(dc *cache.DataCache) *AcmRepositoryCached {
	ns := fmt.Sprintf("%s:%s:acm", r.client.GetAccountID(), r.client.GetRegion())
	return &AcmRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetCertificate returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) GetCertificate(certificateArn string) (*Certificate, error) {
	cacheKey := cache.Key("GetCertificate", certificateArn)
	var cached *Certificate
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCertificate(certificateArn)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetCertificateByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) GetCertificateByInput(query *awsacm.DescribeCertificateInput) (*Certificate, error) {
	cacheKey := cache.Key("GetCertificateByInput", query)
	var cached *Certificate
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCertificateByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetCertificateTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) GetCertificateTags(certificateArn string) (map[string]string, error) {
	cacheKey := cache.Key("GetCertificateTags", certificateArn)
	var cached map[string]string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetCertificateTags(certificateArn)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListCertificatesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) ListCertificatesAll() ([]CertificateSummary, error) {
	cacheKey := cache.Key("ListCertificatesAll")
	var cached []CertificateSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListCertificatesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListCertificatesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) ListCertificatesByInput(query *awsacm.ListCertificatesInput) ([]CertificateSummary, error) {
	cacheKey := cache.Key("ListCertificatesByInput", query)
	var cached []CertificateSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListCertificatesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListCertificatesWithTagsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) ListCertificatesWithTagsAll() ([]CertificateSummary, error) {
	cacheKey := cache.Key("ListCertificatesWithTagsAll")
	var cached []CertificateSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListCertificatesWithTagsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListCertificatesWithTagsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *AcmRepositoryCached) ListCertificatesWithTagsByInput(query *awsacm.ListCertificatesInput) ([]CertificateSummary, error) {
	cacheKey := cache.Key("ListCertificatesWithTagsByInput", query)
	var cached []CertificateSummary
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListCertificatesWithTagsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
