// Code generated by generate-cached. DO NOT EDIT.
package emr

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsemr "github.com/aws/aws-sdk-go-v2/service/emr"
	"github.com/imunhatep/awslib/cache"
	"time"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// EmrRepositoryCached wraps EmrRepository and caches results of Get*/List* calls.
type EmrRepositoryCached struct {
	repo  *EmrRepository
	cache *cache.DataCache
}

// WithCache returns a EmrRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EmrRepository) WithCache(dc *cache.DataCache) *EmrRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EmrRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListClustersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EmrRepositoryCached) ListClustersAll() ([]Cluster, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListClustersAll"
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EmrRepositoryCached) ListClustersByInput(query *awsemr.ListClustersInput) ([]Cluster, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListClustersByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersLatest returns cached results when available, otherwise delegates to the underlying repository.
func (c *EmrRepositoryCached) ListClustersLatest(createdAfter *time.Time) ([]Cluster, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListClustersLatest:%s", strings.Join([]string{fmt.Sprintf("%+v", createdAfter)}, ":")))
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersLatest(createdAfter)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
