// Code generated by generate-cached. DO NOT EDIT.
package emr

import (
	"fmt"

	awsemr "github.com/aws/aws-sdk-go-v2/service/emr"
	"github.com/imunhatep/awslib/cache"
	"time"
)

// EmrRepositoryCached wraps EmrRepository and caches results of Get*/List* calls.
type EmrRepositoryCached struct {
	repo  *EmrRepository
	cache *cache.DataCache
}

// WithCache returns a EmrRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *EmrRepository) WithCache(dc *cache.DataCache) *EmrRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &EmrRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListClustersAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *EmrRepositoryCached) ListClustersAll() ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersAll")
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *EmrRepositoryCached) ListClustersByInput(query *awsemr.ListClustersInput) ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersByInput", query)
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListClustersLatest returns cached results when available, otherwise delegates to the underlying repository.
func (c *EmrRepositoryCached) ListClustersLatest(createdAfter *time.Time) ([]Cluster, error) {
	cacheKey := cache.Key("ListClustersLatest", createdAfter)
	var cached []Cluster
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListClustersLatest(createdAfter)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
