// Code generated by generate-cached. DO NOT EDIT.
package sns

import (
	"fmt"
	"hash/fnv"
	"strings"

	awssns "github.com/aws/aws-sdk-go-v2/service/sns"
	"github.com/aws/aws-sdk-go-v2/service/sns/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// SnsRepositoryCached wraps SnsRepository and caches results of Get*/List* calls.
type SnsRepositoryCached struct {
	repo  *SnsRepository
	cache *cache.DataCache
}

// WithCache returns a SnsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *SnsRepository) WithCache(dc *cache.DataCache) *SnsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &SnsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetTopicTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *SnsRepositoryCached) GetTopicTags(topic types.Topic) ([]types.Tag, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetTopicTags:%s", strings.Join([]string{fmt.Sprintf("%+v", topic)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetTopicTags(topic)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTopicsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *SnsRepositoryCached) ListTopicsAll() ([]Topic, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListTopicsAll"
	var cached []Topic
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTopicsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTopicsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *SnsRepositoryCached) ListTopicsByInput(query *awssns.ListTopicsInput) ([]Topic, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListTopicsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Topic
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTopicsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
