// Code generated by generate-cached. DO NOT EDIT.
package resourcegroupstagging

import (
	"fmt"

	cfg "github.com/aws/aws-sdk-go-v2/service/configservice/types"
	awsrgt "github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi"
	"github.com/imunhatep/awslib/cache"
)

// ResourceGroupsTaggingRepositoryCached wraps ResourceGroupsTaggingRepository and caches results of Get*/List* calls.
type ResourceGroupsTaggingRepositoryCached struct {
	repo  *ResourceGroupsTaggingRepository
	cache *cache.DataCache
}

// WithCache returns a ResourceGroupsTaggingRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:resourcegroupstagging".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *ResourceGroupsTaggingRepository) WithCache(dc *cache.DataCache) *ResourceGroupsTaggingRepositoryCached {
	ns := fmt.Sprintf("%s:%s:resourcegroupstagging", r.client.GetAccountID(), r.client.GetRegion())
	return &ResourceGroupsTaggingRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetResourceTagsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) GetResourceTagsAll() ([]TagMapping, error) {
	cacheKey := cache.Key("GetResourceTagsAll")
	var cached []TagMapping
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetResourceTagsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetResourceTagsByArns returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) GetResourceTagsByArns(arns []string) ([]TagMapping, error) {
	cacheKey := cache.Key("GetResourceTagsByArns", arns)
	var cached []TagMapping
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetResourceTagsByArns(arns)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetResourceTagsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) GetResourceTagsByInput(query *awsrgt.GetResourcesInput) ([]TagMapping, error) {
	cacheKey := cache.Key("GetResourceTagsByInput", query)
	var cached []TagMapping
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetResourceTagsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetResourceTagsByType returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) GetResourceTagsByType(resourceType cfg.ResourceType) ([]TagMapping, error) {
	cacheKey := cache.Key("GetResourceTagsByType", resourceType)
	var cached []TagMapping
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetResourceTagsByType(resourceType)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetResourceTagsByTypes returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) GetResourceTagsByTypes(resourceTypes []cfg.ResourceType) ([]TagMapping, error) {
	cacheKey := cache.Key("GetResourceTagsByTypes", resourceTypes)
	var cached []TagMapping
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetResourceTagsByTypes(resourceTypes)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTagKeys returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) ListTagKeys() ([]string, error) {
	cacheKey := cache.Key("ListTagKeys")
	var cached []string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTagKeys()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTagValues returns cached results when available, otherwise delegates to the underlying repository.
func (c *ResourceGroupsTaggingRepositoryCached) ListTagValues(key string) ([]string, error) {
	cacheKey := cache.Key("ListTagValues", key)
	var cached []string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTagValues(key)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
