// Code generated by generate-cached. DO NOT EDIT.
package savingsplans

import (
	"fmt"

	awssp "github.com/aws/aws-sdk-go-v2/service/savingsplans"
	"github.com/aws/aws-sdk-go-v2/service/savingsplans/types"
	"github.com/imunhatep/awslib/cache"
)

// SavingsPlansRepositoryCached wraps SavingsPlansRepository and caches results of Get*/List* calls.
type SavingsPlansRepositoryCached struct {
	repo  *SavingsPlansRepository
	cache *cache.DataCache
}

// WithCache returns a SavingsPlansRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:savingsplans".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *SavingsPlansRepository) WithCache(dc *cache.DataCache) *SavingsPlansRepositoryCached {
	ns := fmt.Sprintf("%s:%s:savingsplans", r.client.GetAccountID(), r.client.GetRegion())
	return &SavingsPlansRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListOfferingRatesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *SavingsPlansRepositoryCached) ListOfferingRatesByInput(query *awssp.DescribeSavingsPlansOfferingRatesInput) ([]OfferingRate, error) {
	cacheKey := cache.Key("ListOfferingRatesByInput", query)
	var cached []OfferingRate
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListOfferingRatesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListOfferingRatesByQuery returns cached results when available, otherwise delegates to the underlying repository.
func (c *SavingsPlansRepositoryCached) ListOfferingRatesByQuery(query OfferingRatesQuery) ([]OfferingRate, error) {
	cacheKey := cache.Key("ListOfferingRatesByQuery", query)
	var cached []OfferingRate
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListOfferingRatesByQuery(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSavingsPlansAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *SavingsPlansRepositoryCached) ListSavingsPlansAll() ([]types.SavingsPlan, error) {
	cacheKey := cache.Key("ListSavingsPlansAll")
	var cached []types.SavingsPlan
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSavingsPlansAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSavingsPlansByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *SavingsPlansRepositoryCached) ListSavingsPlansByInput(query *awssp.DescribeSavingsPlansInput) ([]types.SavingsPlan, error) {
	cacheKey := cache.Key("ListSavingsPlansByInput", query)
	var cached []types.SavingsPlan
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSavingsPlansByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListSavingsPlansByStates returns cached results when available, otherwise delegates to the underlying repository.
func (c *SavingsPlansRepositoryCached) ListSavingsPlansByStates(states []types.SavingsPlanState) ([]types.SavingsPlan, error) {
	cacheKey := cache.Key("ListSavingsPlansByStates", states)
	var cached []types.SavingsPlan
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListSavingsPlansByStates(states)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
