// Code generated by generate-cached. DO NOT EDIT.
package dynamodb

import (
	"fmt"
	"hash/fnv"
	"strings"

	awsdynamo "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// DynamoDBRepositoryCached wraps DynamoDBRepository and caches results of Get*/List* calls.
type DynamoDBRepositoryCached struct {
	repo  *DynamoDBRepository
	cache *cache.DataCache
}

// WithCache returns a DynamoDBRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *DynamoDBRepository) WithCache(dc *cache.DataCache) *DynamoDBRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &DynamoDBRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetTableTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *DynamoDBRepositoryCached) GetTableTags(table *types.TableDescription) ([]types.Tag, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetTableTags:%s", strings.Join([]string{fmt.Sprintf("%+v", table)}, ":")))
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetTableTags(table)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTablesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *DynamoDBRepositoryCached) ListTablesAll() ([]Table, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListTablesAll"
	var cached []Table
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTablesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTablesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *DynamoDBRepositoryCached) ListTablesByInput(query *awsdynamo.ListTablesInput) ([]Table, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListTablesByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []Table
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTablesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
