// Code generated by generate-cached. DO NOT EDIT.
package dynamodb

import (
	"fmt"

	awsdynamo "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/imunhatep/awslib/cache"
)

// DynamoDBRepositoryCached wraps DynamoDBRepository and caches results of Get*/List* calls.
type DynamoDBRepositoryCached struct {
	repo  *DynamoDBRepository
	cache *cache.DataCache
}

// WithCache returns a DynamoDBRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:dynamodb".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *DynamoDBRepository) WithCache(dc *cache.DataCache) *DynamoDBRepositoryCached {
	ns := fmt.Sprintf("%s:%s:dynamodb", r.client.GetAccountID(), r.client.GetRegion())
	return &DynamoDBRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetTableTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *DynamoDBRepositoryCached) GetTableTags(table *types.TableDescription) ([]types.Tag, error) {
	cacheKey := cache.Key("GetTableTags", table)
	var cached []types.Tag
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetTableTags(table)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTablesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *DynamoDBRepositoryCached) ListTablesAll() ([]Table, error) {
	cacheKey := cache.Key("ListTablesAll")
	var cached []Table
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTablesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListTablesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *DynamoDBRepositoryCached) ListTablesByInput(query *awsdynamo.ListTablesInput) ([]Table, error) {
	cacheKey := cache.Key("ListTablesByInput", query)
	var cached []Table
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListTablesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
