//go:build ignore

// generate-cached scans every package under service/, finds all exported
// *Repository structs and their Get*/List* methods, then emits a
// *RepositoryCached wrapper per package that transparently reads/writes
// through a *cache.DataCache.
//
// Usage:
//
//	go run ./cmd/generate-cached
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

// --------------------------------------------------------------------------
// Data model
// --------------------------------------------------------------------------

type ParamInfo struct {
	Name string
	Type string
}

type MethodInfo struct {
	Name    string
	Params  []ParamInfo
	Results []ParamInfo
	// whether ANY result type contains a channel (skip caching for those)
	HasChan bool
}

// CacheKey returns the Go expression for building the cache key inside the
// wrapper method body. For parameter-less methods: just the method name.
// For methods with params: fnv32 hash of "<MethodName>:<fmt.Sprintf params...>".
func (m MethodInfo) CacheKey() string {
	if len(m.Params) == 0 {
		return fmt.Sprintf("%q", m.Name)
	}
	sprintfArgs := make([]string, len(m.Params))
	for i, p := range m.Params {
		sprintfArgs[i] = fmt.Sprintf("fmt.Sprintf(\"%%+v\", %s)", p.Name)
	}
	raw := fmt.Sprintf(`fmt.Sprintf("%s:%%s", strings.Join([]string{%s}, ":"))`,
		m.Name, strings.Join(sprintfArgs, ", "))
	return fmt.Sprintf("cachedRepoHashKey(%s)", raw)
}

// ResultVars returns comma-separated result variable names (r0, r1, …).
func (m MethodInfo) ResultVars() string {
	var names []string
	for i := range m.Results {
		names = append(names, fmt.Sprintf("r%d", i))
	}
	return strings.Join(names, ", ")
}

// ResultTypes returns comma-separated result types.
func (m MethodInfo) ResultTypes() string {
	var ts []string
	for _, r := range m.Results {
		ts = append(ts, r.Type)
	}
	return strings.Join(ts, ", ")
}

// ParamNames returns comma-separated param variable names for call sites.
func (m MethodInfo) ParamNames() string {
	var names []string
	for _, p := range m.Params {
		names = append(names, p.Name)
	}
	return strings.Join(names, ", ")
}

// ParamSignature returns the full param list for the method signature.
func (m MethodInfo) ParamSignature() string {
	var parts []string
	for _, p := range m.Params {
		parts = append(parts, p.Name+" "+p.Type)
	}
	return strings.Join(parts, ", ")
}

// CacheableResult is the first non-error result (used as the cached value).
func (m MethodInfo) CacheableResult() string {
	for i, r := range m.Results {
		if r.Type != "error" {
			return fmt.Sprintf("r%d", i)
		}
	}
	return "r0"
}

// CacheableResultType is the type of the cacheable result.
func (m MethodInfo) CacheableResultType() string {
	for _, r := range m.Results {
		if r.Type != "error" {
			return r.Type
		}
	}
	return m.Results[0].Type
}

// ErrorVar returns the variable name of the error result.
func (m MethodInfo) ErrorVar() string {
	for i, r := range m.Results {
		if r.Type == "error" {
			return fmt.Sprintf("r%d", i)
		}
	}
	return "_"
}

// HasError reports whether the method returns an error.
func (m MethodInfo) HasError() bool {
	for _, r := range m.Results {
		if r.Type == "error" {
			return true
		}
	}
	return false
}

// HasParams reports whether the method has any parameters.
func (m MethodInfo) HasParams() bool { return len(m.Params) > 0 }

// ImportSpec holds a verbatim import spec copied from the source file.
type ImportSpec struct {
	Alias string // explicit alias (may be empty or "_")
	Path  string // import path without quotes
}

type RepoInfo struct {
	Package      string // e.g. "ec2"
	ImportPath   string // e.g. "github.com/imunhatep/awslib/service/ec2"
	RepoName     string // e.g. "Ec2Repository"
	Methods      []MethodInfo
	ExtraImports []ImportSpec // imports copied verbatim from source files
}

// rawMethod holds the unrendered types.Func for import-path walking.
type rawMethod struct {
	name string
	sig  *types.Signature
}

// --------------------------------------------------------------------------
// Template
// --------------------------------------------------------------------------

const cachedTemplate = `// Code generated by generate-cached. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	"hash/fnv"
	"strings"

	"github.com/imunhatep/awslib/cache"
{{- range .ExtraImports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// {{.RepoName}}Cached wraps {{.RepoName}} and caches results of Get*/List* calls.
type {{.RepoName}}Cached struct {
	repo  *{{.RepoName}}
	cache *cache.DataCache
}

// WithCache returns a {{.RepoName}}Cached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *{{.RepoName}}) WithCache(dc *cache.DataCache) *{{.RepoName}}Cached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &{{.RepoName}}Cached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}
{{range .Methods}}
{{- if .HasChan}}
// {{.Name}} delegates directly to the underlying repository (channel return – not cached).
func (c *{{$.RepoName}}Cached) {{.Name}}({{.ParamSignature}}) ({{.ResultTypes}}) {
	return c.repo.{{.Name}}({{.ParamNames}})
}
{{- else}}
// {{.Name}} returns cached results when available, otherwise delegates to the underlying repository.
func (c *{{$.RepoName}}Cached) {{.Name}}({{.ParamSignature}}) ({{.ResultTypes}}) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := {{.CacheKey}}
	var cached {{.CacheableResultType}}
	if c.cache.Read(cacheKey, &cached) {
		return cached{{if .HasError}}, nil{{end}}
	}
	{{.ResultVars}} := c.repo.{{.Name}}({{.ParamNames}})
{{- if .HasError}}
	if {{.ErrorVar}} == nil {
		_ = c.cache.Write(cacheKey, {{.CacheableResult}})
	}
{{- end}}
	return {{.ResultVars}}
}
{{- end}}
{{end}}`

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

func zeroValue(t string) string {
	switch {
	case t == "error":
		return "nil"
	case strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "map[") ||
		strings.HasPrefix(t, "*") || strings.HasPrefix(t, "<-chan") ||
		strings.HasPrefix(t, "chan"):
		return "nil"
	case t == "bool":
		return "false"
	case t == "int" || t == "int32" || t == "int64" ||
		t == "uint" || t == "uint32" || t == "uint64":
		return "0"
	case t == "string":
		return `""`
	default:
		return fmt.Sprintf("%s{}", t)
	}
}

// typeString converts a types.Type to a Go source string.
// It uses the provided alias map (pkgPath → local alias) to render qualifiers
// exactly as they appear in the original source files.
func typeString(t types.Type, pkgPath string, aliasMap map[string]string) string {
	switch v := t.(type) {
	case *types.Named:
		obj := v.Obj()
		if obj.Pkg() == nil || obj.Pkg().Path() == pkgPath {
			return obj.Name()
		}
		path := obj.Pkg().Path()
		if alias, ok := aliasMap[path]; ok && alias != "" {
			return alias + "." + obj.Name()
		}
		return obj.Pkg().Name() + "." + obj.Name()
	case *types.Pointer:
		return "*" + typeString(v.Elem(), pkgPath, aliasMap)
	case *types.Slice:
		return "[]" + typeString(v.Elem(), pkgPath, aliasMap)
	case *types.Map:
		return "map[" + typeString(v.Key(), pkgPath, aliasMap) + "]" + typeString(v.Elem(), pkgPath, aliasMap)
	case *types.Chan:
		switch v.Dir() {
		case types.RecvOnly:
			return "<-chan " + typeString(v.Elem(), pkgPath, aliasMap)
		case types.SendOnly:
			return "chan<- " + typeString(v.Elem(), pkgPath, aliasMap)
		default:
			return "chan " + typeString(v.Elem(), pkgPath, aliasMap)
		}
	case *types.Basic:
		return v.Name()
	case *types.Interface:
		if v.Empty() {
			return "interface{}"
		}
		return v.String()
	default:
		return t.String()
	}
}

func hasChan(t types.Type) bool {
	switch v := t.(type) {
	case *types.Chan:
		return true
	case *types.Pointer:
		return hasChan(v.Elem())
	default:
		_ = v
		return false
	}
}

// buildAliasMap builds pkgPath → localAlias from all NON-GENERATED source
// files in the package.
// Rule: an explicit alias always beats a no-alias entry, regardless of file
// processing order. "" means "use pkg.Name()".
func buildAliasMap(pkg *packages.Package) map[string]string {
	m := map[string]string{}
	for _, f := range pkg.Syntax {
		// Skip generated files to avoid picking up stale aliases
		if isGeneratedFile(pkg.Fset, f) {
			continue
		}
		for _, imp := range f.Imports {
			path := strings.Trim(imp.Path.Value, `"`)
			alias := ""
			if imp.Name != nil && imp.Name.Name != "_" && imp.Name.Name != "." {
				alias = imp.Name.Name
			}
			prev, exists := m[path]
			if !exists || (alias != "" && prev == "") {
				// First time seeing this path, or we now have an explicit alias
				// that upgrades a previously-recorded no-alias entry.
				m[path] = alias
			}
		}
	}
	return m
}

// isGeneratedFile reports whether an AST file was produced by a code generator
// (contains the "DO NOT EDIT" marker in its first comment group).
func isGeneratedFile(fset *token.FileSet, f *ast.File) bool {
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "DO NOT EDIT") {
				return true
			}
		}
		// Only check the first comment group near the top of the file
		if fset.Position(cg.Pos()).Line > 5 {
			break
		}
	}
	return false
}

// collectRequiredImports walks the raw method signatures, collects all
// external package paths referenced, then returns verbatim ImportSpec values
// copied from the source files' AST import specs.
//
// Excluded:
//   - the package itself
//   - internal client helpers  (provider/v3/clients/…)
//   - cache package (hard-coded in template)
func collectRequiredImports(
	raws []rawMethod,
	pkg *packages.Package,
	aliasMap map[string]string,
) []ImportSpec {
	// 1. Walk types to collect needed package paths
	needed := map[string]bool{}
	var walk func(t types.Type)
	walk = func(t types.Type) {
		switch v := t.(type) {
		case *types.Named:
			p := v.Obj().Pkg()
			if p == nil || p.Path() == pkg.PkgPath {
				return
			}
			needed[p.Path()] = true
		case *types.Pointer:
			walk(v.Elem())
		case *types.Slice:
			walk(v.Elem())
		case *types.Map:
			walk(v.Key())
			walk(v.Elem())
		case *types.Chan:
			walk(v.Elem())
		}
	}
	for _, rm := range raws {
		for i := 0; i < rm.sig.Params().Len(); i++ {
			walk(rm.sig.Params().At(i).Type())
		}
		for i := 0; i < rm.sig.Results().Len(); i++ {
			walk(rm.sig.Results().At(i).Type())
		}
	}

	// 2. Build verbatim import specs from non-generated source files.
	// Explicit alias always beats a no-alias entry for the same path.
	specByPath := map[string]ImportSpec{}
	for _, f := range pkg.Syntax {
		if isGeneratedFile(pkg.Fset, f) {
			continue
		}
		for _, imp := range f.Imports {
			path := strings.Trim(imp.Path.Value, `"`)
			alias := ""
			if imp.Name != nil && imp.Name.Name != "_" && imp.Name.Name != "." {
				alias = imp.Name.Name
			}
			prev, exists := specByPath[path]
			if !exists || (alias != "" && prev.Alias == "") {
				specByPath[path] = ImportSpec{Alias: alias, Path: path}
			}
		}
	}

	// 3. Filter to only paths actually needed and not excluded
	var out []ImportSpec
	for path := range needed {
		if strings.Contains(path, "provider/v3/clients") {
			continue
		}
		if path == "github.com/imunhatep/awslib/cache" {
			continue
		}
		spec, ok := specByPath[path]
		if !ok {
			// Fallback: no verbatim spec found, emit path only
			spec = ImportSpec{Path: path}
		}
		out = append(out, spec)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

// --------------------------------------------------------------------------
// Main
// --------------------------------------------------------------------------

func main() {
	moduleRoot := "."
	serviceDir := filepath.Join(moduleRoot, "service")

	entries, err := os.ReadDir(serviceDir)
	if err != nil {
		fatalf("read service dir: %v", err)
	}

	// Delete stale generated files before loading so they don't pollute alias maps
	cleanGeneratedFiles(serviceDir)

	tmpl, err := template.New("cached").Parse(cachedTemplate)
	if err != nil {
		fatalf("parse template: %v", err)
	}

	generated := 0

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		pkgDir := filepath.Join(serviceDir, entry.Name())
		pkgPattern := "./" + pkgDir

		cfg := &packages.Config{
			Mode: packages.NeedName |
				packages.NeedFiles |
				packages.NeedSyntax |
				packages.NeedTypes |
				packages.NeedTypesInfo |
				packages.NeedImports,
			Fset: token.NewFileSet(),
		}

		pkgs, err := packages.Load(cfg, pkgPattern)
		if err != nil {
			fmt.Printf("⚠  skip %s: load error: %v\n", pkgDir, err)
			continue
		}
		if len(pkgs) == 0 {
			continue
		}

		pkg := pkgs[0]
		if len(pkg.Errors) > 0 {
			fmt.Printf("⚠  skip %s: package errors:\n", pkgDir)
			for _, e := range pkg.Errors {
				fmt.Printf("    %v\n", e)
			}
			continue
		}

		// Build alias map from non-generated source files only
		aliasMap := buildAliasMap(pkg)

		// Collect all Repository structs and their Get*/List* methods
		repoMethods := map[string][]MethodInfo{}
		repoRaws := map[string][]rawMethod{}

		scope := pkg.Types.Scope()
		for _, name := range scope.Names() {
			obj := scope.Lookup(name)
			if obj == nil {
				continue
			}
			typeName, ok := obj.(*types.TypeName)
			if !ok || !typeName.Exported() || !strings.HasSuffix(name, "Repository") {
				continue
			}
			named, ok := typeName.Type().(*types.Named)
			if !ok {
				continue
			}
			if _, ok := named.Underlying().(*types.Struct); !ok {
				continue
			}

			ptrType := types.NewPointer(named)
			mset := types.NewMethodSet(ptrType)
			for i := 0; i < mset.Len(); i++ {
				sel := mset.At(i)
				fn, ok := sel.Obj().(*types.Func)
				if !ok || !fn.Exported() {
					continue
				}
				if !strings.HasPrefix(fn.Name(), "Get") && !strings.HasPrefix(fn.Name(), "List") {
					continue
				}
				if fn.Name() == "GetRegion" || fn.Name() == "GetAccountID" {
					continue
				}

				sig := fn.Type().(*types.Signature)
				var params []ParamInfo
				for j := 0; j < sig.Params().Len(); j++ {
					p := sig.Params().At(j)
					params = append(params, ParamInfo{
						Name: paramName(p.Name(), j),
						Type: typeString(p.Type(), pkg.PkgPath, aliasMap),
					})
				}

				var results []ParamInfo
				anyChan := false
				for j := 0; j < sig.Results().Len(); j++ {
					r := sig.Results().At(j)
					ts := typeString(r.Type(), pkg.PkgPath, aliasMap)
					results = append(results, ParamInfo{
						Name: fmt.Sprintf("r%d", j),
						Type: ts,
					})
					if hasChan(r.Type()) {
						anyChan = true
					}
				}
				if len(results) == 0 {
					continue
				}

				repoMethods[name] = append(repoMethods[name], MethodInfo{
					Name:    fn.Name(),
					Params:  params,
					Results: results,
					HasChan: anyChan,
				})
				repoRaws[name] = append(repoRaws[name], rawMethod{name: fn.Name(), sig: sig})
			}
		}

		if len(repoMethods) == 0 {
			continue
		}

		var repoNames []string
		for n := range repoMethods {
			repoNames = append(repoNames, n)
		}
		sort.Strings(repoNames)

		for _, repoName := range repoNames {
			methods := repoMethods[repoName]
			sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })

			info := RepoInfo{
				Package:      pkg.Name,
				ImportPath:   pkg.PkgPath,
				RepoName:     repoName,
				Methods:      methods,
				ExtraImports: collectRequiredImports(repoRaws[repoName], pkg, aliasMap),
			}

			outPath := filepath.Join(pkgDir, "cached_repository.go")
			if len(repoNames) > 1 {
				safeName := strings.ToLower(strings.TrimSuffix(repoName, "Repository"))
				outPath = filepath.Join(pkgDir, "cached_"+safeName+"_repository.go")
			}

			var buf bytes.Buffer
			if err := tmpl.Execute(&buf, info); err != nil {
				fatalf("execute template for %s/%s: %v", pkg.Name, repoName, err)
			}

			formatted, err := format.Source(buf.Bytes())
			if err != nil {
				_ = os.WriteFile(outPath, buf.Bytes(), 0644)
				fmt.Printf("⚠  %s/%s: format error (raw file written): %v\n", pkg.Name, repoName, err)
				continue
			}

			if err := os.WriteFile(outPath, formatted, 0644); err != nil {
				fatalf("write %s: %v", outPath, err)
			}

			fmt.Printf("✓  generated %s\n", outPath)
			generated++
		}
	}

	fmt.Printf("\n✓  Total: %d file(s) generated\n", generated)
}

// cleanGeneratedFiles removes previously generated cached_*_repository.go
// files so stale content does not pollute alias maps on re-runs.
func cleanGeneratedFiles(serviceDir string) {
	_ = filepath.WalkDir(serviceDir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		name := d.Name()
		if strings.HasPrefix(name, "cached_") && strings.HasSuffix(name, "_repository.go") {
			_ = os.Remove(path)
			return nil
		}
		if name == "cached_repository.go" {
			_ = os.Remove(path)
		}
		return nil
	})
}

func paramName(name string, idx int) string {
	if name == "" || name == "_" {
		return fmt.Sprintf("p%d", idx)
	}
	return name
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", args...)
	os.Exit(1)
}
