// Code generated by generate-cached. DO NOT EDIT.
package cloudtrail

import (
	"fmt"

	awscloudtrail "github.com/aws/aws-sdk-go-v2/service/cloudtrail"
	"github.com/go-errors/errors"
	"github.com/imunhatep/awslib/cache"
)

// CloudTrailRepositoryCached wraps CloudTrailRepository and caches results of Get*/List* calls.
type CloudTrailRepositoryCached struct {
	repo  *CloudTrailRepository
	cache *cache.DataCache
}

// WithCache returns a CloudTrailRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *CloudTrailRepository) WithCache(dc *cache.DataCache) *CloudTrailRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &CloudTrailRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListEventsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudTrailRepositoryCached) ListEventsByInput(query *awscloudtrail.LookupEventsInput) ([]Event, error) {
	cacheKey := cache.Key("ListEventsByInput", query)
	var cached []Event
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListEventsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListEventsByInputAsync delegates directly to the underlying repository (channel return – not cached).
func (c *CloudTrailRepositoryCached) ListEventsByInputAsync(query *awscloudtrail.LookupEventsInput) (<-chan Event, <-chan *errors.Error) {
	return c.repo.ListEventsByInputAsync(query)
}

// ListEventsByLookup returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudTrailRepositoryCached) ListEventsByLookup(lookup *LookupMiddleware) ([]Event, error) {
	cacheKey := cache.Key("ListEventsByLookup", lookup)
	var cached []Event
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListEventsByLookup(lookup)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListEventsByLookupAsync delegates directly to the underlying repository (channel return – not cached).
func (c *CloudTrailRepositoryCached) ListEventsByLookupAsync(lookup *LookupMiddleware) (<-chan Event, <-chan *errors.Error) {
	return c.repo.ListEventsByLookupAsync(lookup)
}

// ListEventsByLookupCached returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudTrailRepositoryCached) ListEventsByLookupCached(p0 *cache.DataCache, lookup *LookupMiddleware) ([]Event, error) {
	cacheKey := cache.Key("ListEventsByLookupCached", lookup)
	var cached []Event
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListEventsByLookupCached(p0, lookup)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
