// Code generated by generate-cached. DO NOT EDIT.
package rds

import (
	"fmt"

	awsrds "github.com/aws/aws-sdk-go-v2/service/rds"
	"github.com/aws/aws-sdk-go-v2/service/rds/types"
	"github.com/imunhatep/awslib/cache"
)

// RdsRepositoryCached wraps RdsRepository and caches results of Get*/List* calls.
type RdsRepositoryCached struct {
	repo  *RdsRepository
	cache *cache.DataCache
}

// WithCache returns a RdsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *RdsRepository) WithCache(dc *cache.DataCache) *RdsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &RdsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// ListDBEngineVersionsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *RdsRepositoryCached) ListDBEngineVersionsByInput(query *awsrds.DescribeDBEngineVersionsInput) ([]types.DBEngineVersion, error) {
	cacheKey := cache.Key("ListDBEngineVersionsByInput", query)
	var cached []types.DBEngineVersion
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDBEngineVersionsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDbInstancesAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *RdsRepositoryCached) ListDbInstancesAll() ([]DbInstance, error) {
	cacheKey := cache.Key("ListDbInstancesAll")
	var cached []DbInstance
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDbInstancesAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDbInstancesByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *RdsRepositoryCached) ListDbInstancesByInput(query *awsrds.DescribeDBInstancesInput) ([]DbInstance, error) {
	cacheKey := cache.Key("ListDbInstancesByInput", query)
	var cached []DbInstance
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDbInstancesByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDbSnapshotsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *RdsRepositoryCached) ListDbSnapshotsAll() ([]DbSnapshot, error) {
	cacheKey := cache.Key("ListDbSnapshotsAll")
	var cached []DbSnapshot
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDbSnapshotsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListDbSnapshotsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *RdsRepositoryCached) ListDbSnapshotsByInput(query *awsrds.DescribeDBSnapshotsInput) ([]DbSnapshot, error) {
	cacheKey := cache.Key("ListDbSnapshotsByInput", query)
	var cached []DbSnapshot
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListDbSnapshotsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
