// Code generated by generate-cached. DO NOT EDIT.
package cloudwatchlogs

import (
	"fmt"

	awscloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	"github.com/imunhatep/awslib/cache"
)

// CloudWatchLogsRepositoryCached wraps CloudWatchLogsRepository and caches results of Get*/List* calls.
type CloudWatchLogsRepositoryCached struct {
	repo  *CloudWatchLogsRepository
	cache *cache.DataCache
}

// WithCache returns a CloudWatchLogsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:cloudwatchlogs".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *CloudWatchLogsRepository) WithCache(dc *cache.DataCache) *CloudWatchLogsRepositoryCached {
	ns := fmt.Sprintf("%s:%s:cloudwatchlogs", r.client.GetAccountID(), r.client.GetRegion())
	return &CloudWatchLogsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetLogGroupTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudWatchLogsRepositoryCached) GetLogGroupTags(logGroup types.LogGroup) (map[string]string, error) {
	cacheKey := cache.Key("GetLogGroupTags", logGroup)
	var cached map[string]string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetLogGroupTags(logGroup)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListLogGroupsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudWatchLogsRepositoryCached) ListLogGroupsAll() ([]LogGroup, error) {
	cacheKey := cache.Key("ListLogGroupsAll")
	var cached []LogGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListLogGroupsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListLogGroupsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudWatchLogsRepositoryCached) ListLogGroupsByInput(query *awscloudwatchlogs.DescribeLogGroupsInput) ([]LogGroup, error) {
	cacheKey := cache.Key("ListLogGroupsByInput", query)
	var cached []LogGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListLogGroupsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
