// Code generated by generate-cached. DO NOT EDIT.
package cloudwatchlogs

import (
	"fmt"
	"hash/fnv"
	"strings"

	awscloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	"github.com/imunhatep/awslib/cache"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// CloudWatchLogsRepositoryCached wraps CloudWatchLogsRepository and caches results of Get*/List* calls.
type CloudWatchLogsRepositoryCached struct {
	repo  *CloudWatchLogsRepository
	cache *cache.DataCache
}

// WithCache returns a CloudWatchLogsRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *CloudWatchLogsRepository) WithCache(dc *cache.DataCache) *CloudWatchLogsRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &CloudWatchLogsRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetLogGroupTags returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudWatchLogsRepositoryCached) GetLogGroupTags(logGroup types.LogGroup) (map[string]string, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetLogGroupTags:%s", strings.Join([]string{fmt.Sprintf("%+v", logGroup)}, ":")))
	var cached map[string]string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetLogGroupTags(logGroup)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListLogGroupsAll returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudWatchLogsRepositoryCached) ListLogGroupsAll() ([]LogGroup, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := "ListLogGroupsAll"
	var cached []LogGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListLogGroupsAll()
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// ListLogGroupsByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *CloudWatchLogsRepositoryCached) ListLogGroupsByInput(query *awscloudwatchlogs.DescribeLogGroupsInput) ([]LogGroup, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("ListLogGroupsByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []LogGroup
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.ListLogGroupsByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
