// Code generated by generate-cached. DO NOT EDIT.
package pricing

import (
	"fmt"

	ec2types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	awspricing "github.com/aws/aws-sdk-go-v2/service/pricing"
	"github.com/imunhatep/awslib/cache"
	ptypes "github.com/imunhatep/awslib/provider/types"
)

// PricingRepositoryCached wraps PricingRepository and caches results of Get*/List* calls.
type PricingRepositoryCached struct {
	repo  *PricingRepository
	cache *cache.DataCache
}

// WithCache returns a PricingRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>:pricing".
//
// The service name is part of the namespace because cache.Key renders a parameterless
// call as the bare method name, and several services expose the same one: ListClustersAll
// on ecs/eks/emr, ListTablesAll on dynamodb/glue. Sharing a namespace makes those
// repositories overwrite each other's entries, so every read decodes another service's
// payload, fails, and refetches from AWS.
func (r *PricingRepository) WithCache(dc *cache.DataCache) *PricingRepositoryCached {
	ns := fmt.Sprintf("%s:%s:pricing", r.client.GetAccountID(), r.client.GetRegion())
	return &PricingRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetInstancePricing returns cached results when available, otherwise delegates to the underlying repository.
func (c *PricingRepositoryCached) GetInstancePricing(region ptypes.AwsRegion, instanceType ec2types.InstanceType) (*Ec2Product, error) {
	cacheKey := cache.Key("GetInstancePricing", region, instanceType)
	var cached *Ec2Product
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetInstancePricing(region, instanceType)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetInstancePricingByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *PricingRepositoryCached) GetInstancePricingByInput(query *awspricing.GetProductsInput) ([]string, error) {
	cacheKey := cache.Key("GetInstancePricingByInput", query)
	var cached []string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetInstancePricingByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
