// Code generated by generate-cached. DO NOT EDIT.
package pricing

import (
	"fmt"
	"hash/fnv"
	"strings"

	ec2types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	awspricing "github.com/aws/aws-sdk-go-v2/service/pricing"
	"github.com/imunhatep/awslib/cache"
	ptypes "github.com/imunhatep/awslib/provider/types"
)

// cachedRepoHashKey returns a short, file-safe FNV-32 hex hash of the given string,
// prefixed by the method name component for readability.
func cachedRepoHashKey(raw string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(raw))
	return fmt.Sprintf("%x", h.Sum32())
}

// PricingRepositoryCached wraps PricingRepository and caches results of Get*/List* calls.
type PricingRepositoryCached struct {
	repo  *PricingRepository
	cache *cache.DataCache
}

// WithCache returns a PricingRepositoryCached that stores/retrieves results via the given DataCache.
// The cache namespace is set to "<accountID>:<region>".
func (r *PricingRepository) WithCache(dc *cache.DataCache) *PricingRepositoryCached {
	ns := fmt.Sprintf("%s:%s", r.client.GetAccountID(), r.client.GetRegion())
	return &PricingRepositoryCached{
		repo:  r,
		cache: dc.WithNamespace(ns),
	}
}

// GetInstancePricing returns cached results when available, otherwise delegates to the underlying repository.
func (c *PricingRepositoryCached) GetInstancePricing(region ptypes.AwsRegion, instanceType ec2types.InstanceType) (*Ec2Product, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetInstancePricing:%s", strings.Join([]string{fmt.Sprintf("%+v", region), fmt.Sprintf("%+v", instanceType)}, ":")))
	var cached *Ec2Product
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetInstancePricing(region, instanceType)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}

// GetInstancePricingByInput returns cached results when available, otherwise delegates to the underlying repository.
func (c *PricingRepositoryCached) GetInstancePricingByInput(query *awspricing.GetProductsInput) ([]string, error) {
	_ = strings.Join // used by cachedRepoHashKey helper when params are present
	cacheKey := cachedRepoHashKey(fmt.Sprintf("GetInstancePricingByInput:%s", strings.Join([]string{fmt.Sprintf("%+v", query)}, ":")))
	var cached []string
	if c.cache.Read(cacheKey, &cached) {
		return cached, nil
	}
	r0, r1 := c.repo.GetInstancePricingByInput(query)
	if r1 == nil {
		_ = c.cache.Write(cacheKey, r0)
	}
	return r0, r1
}
