// Code generated by cmd/generate-gob/main.go; DO NOT EDIT.

package pricing

import "encoding/gob"

// init registers this package's types with encoding/gob so they can be
// serialized by the cache handlers. Importing this package is sufficient.
func init() {
	gob.Register(Attributes{})
	gob.Register(Ec2Product{})
	gob.Register(PriceDimension{})
	gob.Register(PricePerUnit{})
	gob.Register(Product{})
	gob.Register(Term{})
	gob.Register(TermAttributes{})
	gob.Register(Terms{})
}
